import { createBazframeTuiService } from '../../../src/application/tui-service.js';
import { VERSION } from '../../../src/cli/help.js';
import { readlink } from 'node:fs/promises';
import { readlinkSync, mkdirSync, writeFileSync } from 'node:fs';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { windowsGitHostFixture } from '../../helpers/windows-git-host-fixture.js';
import { createWindowsApplicationServices } from '../../../src/application/win32-application-services.js';
import { runCliForInternalTesting } from '../../../src/cli/run-cli.js';
vi.mock('node:fs/promises', async (original) => { const actual = await original<typeof import('node:fs/promises')>(); return { ...actual, readlink: vi.fn(actual.readlink) }; });
const fixtures: ReturnType<typeof windowsGitHostFixture>[] = [];
afterEach(() => { for (const f of fixtures.splice(0)) f.cleanup(); });

describe('Windows CLI provider composition with actual disposable local Git', () => {
  it('acquires W6 operation authority per mutation across resource acquisition/references/update/build/removal', async () => {
    const f = windowsGitHostFixture(); fixtures.push(f);
    vi.mocked(readlink).mockImplementation(async (path) => f.windowsPath(readlinkSync(f.hostPath(String(path)))));
    const backend = Object.assign(f.backend, { inspectEditorTarget(): never { throw new Error('no editor operation in provider journey'); } });
    const environment = { BAZFRAME_HOME: 'C:\\boundary\\home' };
    const application = createWindowsApplicationServices({ ...f.options, journal: { io: f.io }, backend: () => backend, environment, profileProcess: f.profileProcess, zip: { temporaryRoot: 'C:\\boundary', io: { async *readInput(path) { yield f.nodes.get(path)!.bytes!; }, async writeExistingFile(path, chunks) { const bytes: Buffer[] = []; for await (const chunk of chunks) bytes.push(Buffer.from(chunk)); await f.io.writeExistingFile(path, Buffer.concat(bytes)); }, rename: f.io.rename } } });
    const command = async (argv: string[]) => { let output = '', error = ''; const status = await runCliForInternalTesting([...argv, '--json'], { application, environment, cwd: () => 'C:\\boundary', writeStdout: (text) => { output += text; }, writeStderr: (text) => { error += text; } }); expect(status, `${argv.join(' ')}: ${error || output}`).toBe(0); return output; };
    const library = f.source('remote-library', { 'hello/SKILL.md': '---\nname: hello\ndescription: Local Git library\n---\n', 'hello/helper': Buffer.from([255, 0, 13, 10]) }, ['hello/helper']);
    const skill = f.source('remote-skill', { 'SKILL.md': '---\nname: remote-skill\ndescription: Local Git Skill\n---\n', helper: 'tracked\r\n' }, ['helper']);
    const pkg = f.source('remote-package', { 'bazframe-package.json': JSON.stringify({ schemaVersion: 1, build: ['node', 'build.cjs'], artifactRoot: 'dist', skillsRoot: '.' }), 'build.cjs': "const fs=require('node:fs');fs.mkdirSync('dist/built',{recursive:true});fs.writeFileSync('dist/built/SKILL.md','---\\nname: built\\ndescription: Actual local build\\n---\\n');" });
    await command(['profile', 'add', 'work']); await command(['profile', 'use', 'work']);
    await command(['library', 'add', library.url]);
    await command(['skill', 'add', skill.url]);
    await command(['package', 'add', pkg.url, '--yes']);
    await command(['profile', 'library', 'add', 'remote-library']);
    await command(['profile', 'skill', 'add', 'remote-skill']);
    await command(['profile', 'package', 'add', 'remote-package']);
    expect(await command(['library', 'list'])).toContain('remote-library');
    expect(await command(['package', 'list'])).toContain('built');
    await command(['library', 'update', 'remote-library']); await command(['skill', 'update', 'remote-skill']);
    await command(['package', 'update', 'remote-package', '--yes']); await command(['package', 'build', 'remote-package']);
    await command(['profile', 'export', '--output', 'C:\\boundary\\work.zip', '--bundle-remote']);
    await command(['profile', 'import', 'C:\\boundary\\work.zip', '--yes']); await command(['profile', 'use', 'work-1']);
    const importedSkills = 'C:\\boundary\\home\\profiles\\work-1\\skills'; expect(f.nodes.has(importedSkills)).toBe(false);
    const secondPackage = f.source('second-package', { 'bazframe-package.json': JSON.stringify({ schemaVersion: 1, build: ['node', 'build.cjs'], artifactRoot: 'dist', skillsRoot: '.' }), 'build.cjs': "const fs=require('node:fs');fs.mkdirSync('dist/second-built',{recursive:true});fs.writeFileSync('dist/second-built/SKILL.md','---\\nname: second-built\\ndescription: Additional actual build\\n---\\n');" });
    await command(['package', 'add', secondPackage.url, '--yes']); await command(['profile', 'package', 'add', 'second-package']);
    expect(f.nodes.has(importedSkills)).toBe(false);
    const secondLibrary = f.source('second-library', { 'second/SKILL.md': '---\nname: second\ndescription: Additional library\n---\n' });
    await command(['library', 'add', secondLibrary.url]); await command(['profile', 'library', 'add', 'second-library']); expect(f.nodes.has(importedSkills)).toBe(false);
    const secondSkill = f.source('second-skill', { 'SKILL.md': '---\nname: second-skill\ndescription: Additional Skill\n---\n' }); await command(['skill', 'add', secondSkill.url]); await command(['profile', 'skill', 'add', 'second-skill']); expect(f.nodes.has(importedSkills)).toBe(true);
    const tui = createBazframeTuiService({ bazframeHome: environment.BAZFRAME_HOME, bazframeVersion: VERSION, cwd: 'C:\\boundary', environment, application });
    const dashboard = await tui.loadDashboard(); const imported = dashboard.profiles.find((profile) => profile.id === 'work-1')!;
    expect(imported.libraryReferences).toEqual(expect.arrayContaining([expect.objectContaining({ id: 'second-library', availability: 'available' })]));
    expect(imported.packageReferences).toEqual(expect.arrayContaining([expect.objectContaining({ id: 'second-package', availability: 'available' })]));
    await command(['profile', 'use', 'work']);
    const localPackage = 'C:\\boundary\\local-package'; mkdirSync(f.hostPath(localPackage));
    writeFileSync(f.hostPath(localPackage + '\\bazframe-package.json'), JSON.stringify({ schemaVersion: 1, build: ['node', 'build.cjs'], artifactRoot: 'dist', skillsRoot: '.' }));
    writeFileSync(f.hostPath(localPackage + '\\build.cjs'), "const fs=require('node:fs');fs.mkdirSync('dist/local-built',{recursive:true});fs.writeFileSync('dist/local-built/SKILL.md','---\\nname: local-built\\ndescription: Local source build\\n---\\n');"); f.refresh();
    expect(await command(['package', 'add', localPackage])).toContain('"sourceType":"local"'); await command(['package', 'build', 'local-package']); await command(['package', 'remove', 'local-package']);
    await command(['profile', 'duplicate', 'work', 'copy']);
    await command(['profile', 'remove', 'copy', '--force']);
    await command(['profile', 'library', 'remove', 'remote-library']); await command(['profile', 'skill', 'remove', 'remote-skill']); await command(['profile', 'package', 'remove', 'remote-package']);
    await command(['library', 'remove', 'remote-library']); await command(['skill', 'remove', 'remote-skill']); await command(['package', 'remove', 'remote-package']);
    expect(f.requests.some((request) => request.args.includes('clone'))).toBe(true);
    expect(f.requests.every((request) => request.executable === '/usr/bin/git')).toBe(true);
  }, 120000);
  it('connects CLI publication/import/update/version through production runtime and actual local canonical Git', async () => {
    const f = windowsGitHostFixture(); fixtures.push(f);
    vi.mocked(readlink).mockImplementation(async (path) => f.windowsPath(readlinkSync(f.hostPath(String(path)))));
    const github = f.github('owner/work');
    const backend = Object.assign(f.backend, { inspectEditorTarget(): never { throw new Error('no editor in canonical journey'); } });
    const environment = { BAZFRAME_HOME: 'C:\\boundary\\home', AppData: 'C:\\boundary\\appdata' };
    const application = createWindowsApplicationServices({ ...f.options, journal: { io: f.io }, backend: () => backend, environment, profileProcess: async (request) => { expect(request.environment.GH_CONFIG_DIR).toBe('C:\\boundary\\appdata\\GitHub CLI'); expect(request.environment.HOME).not.toBe(environment.AppData); return github.process(request); }, zip: { temporaryRoot: 'C:\\boundary', io: f.zipIo } });
    const command = async (argv: string[]) => { let output = ''; const status = await runCliForInternalTesting([...argv, '--json'], { application, environment, cwd: () => 'C:\\boundary', temporaryRoot: 'C:\\boundary', writeStdout: (text) => { output += text; }, writeStderr() {} }); expect(status, `${argv.join(' ')}: ${output}`).toBe(0); return JSON.parse(output); };
    await command(['profile', 'add', 'work']); await command(['profile', 'use', 'work']);
    const published = await command(['profile', 'publish', '--yes']);
    expect(published.outcome).toBe('success');
    const listed = await command(['profile', 'version', 'list']); expect(listed.result.versions).toHaveLength(1);
    await command(['profile', 'update']); await command(['profile', 'version', 'use', listed.result.versions[0].commit]);
    const current = await command(['profile', 'import', 'git:owner/work', '--yes']); expect(current.result.effects.profilePublished).toBe(false);
    await command(['profile', 'add', 'holding']); await command(['profile', 'use', 'holding']); await command(['profile', 'remove', 'work', '--force']);
    const imported = await command(['profile', 'import', 'git:owner/work', '--yes']); expect(imported.result.effects.profilePublished).toBe(true); await command(['profile', 'use', imported.result.resolvedName]);
    expect(f.nodes.has('C:\\boundary\\appdata')).toBe(false);
    expect(f.requests.some((request) => request.args.includes('push'))).toBe(true);
    expect(f.requests.some((request) => request.args.includes('fetch'))).toBe(true);
  }, 120000);

});
