import { randomUUID } from 'node:crypto';
import { constants } from 'node:fs';
import { link, lstat, open, rmdir, unlink, type FileHandle } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { readUtf8InstructionFile } from '../core/content.js';
import { BazframeError, errorCode } from '../core/errors.js';
import { loadFlatSkillIdentities, validateProspectiveSkillCollection, type DirectSkillCollection } from '../skill-collections/skill-collection-resolver.js';
import { globalCollectionPath, idForRecord, kindForRecord, readCollectionSnapshot, sameCollectionSnapshot, skillsRootForRecord, type SkillCollectionKey, type SkillCollectionRecord } from '../skill-collections/skill-collection-store.js';
import { verifySkillSnapshot } from '../skill-collections/skill-snapshot.js';
import { assertSafeSkillId } from '../skills/skill-id.js';
import { ensureManagedDirectory } from '../state/atomic-file.js';
import { withStateLock } from '../state/lock.js';
import { assertSafeProfileId } from './profile-id.js';
import { encodeProfileCollectionReference, profileCollectionDirectory, profileCollectionReferencePath, readProfileCollectionReferenceSnapshot, sameProfileCollectionReferenceSnapshot, scanProfileCollectionReferences, type ProfileSkillCollectionReference, type ProfileSkillCollectionReferenceSnapshot } from './profile-skill-collection-reference.js';
import { discoverSkillDirectories, profileDirectory, readActiveProfile } from './profile-store.js';

export interface ProfileCollectionReferenceOptions { bazframeHome:string }
export type ProfileCollectionReferenceAction='added'|'current'|'removed'|'absent';
export type ProfileCollectionReferenceResult=ProfileSkillCollectionReference&{action:ProfileCollectionReferenceAction;profileId:string;path:string};
export function addActiveProfileLibraryReference(options:ProfileCollectionReferenceOptions,id:string){return addFor(options,undefined,{kind:'library',id} as const);}
export function addProfileLibraryReference(options:ProfileCollectionReferenceOptions,profileId:string,id:string){assertSafeProfileId(profileId);return addFor(options,profileId,{kind:'library',id} as const);}
export function removeActiveProfileLibraryReference(options:ProfileCollectionReferenceOptions,id:string){return removeFor(options,undefined,{kind:'library',id} as const);}
export function removeProfileLibraryReference(options:ProfileCollectionReferenceOptions,profileId:string,id:string){assertSafeProfileId(profileId);return removeFor(options,profileId,{kind:'library',id} as const);}
export function addActiveProfilePackageReference(options:ProfileCollectionReferenceOptions,id:string){return addFor(options,undefined,{kind:'package',id} as const);}
export function addProfilePackageReference(options:ProfileCollectionReferenceOptions,profileId:string,id:string){assertSafeProfileId(profileId);return addFor(options,profileId,{kind:'package',id} as const);}
export function removeActiveProfilePackageReference(options:ProfileCollectionReferenceOptions,id:string){return removeFor(options,undefined,{kind:'package',id} as const);}
export function removeProfilePackageReference(options:ProfileCollectionReferenceOptions,profileId:string,id:string){assertSafeProfileId(profileId);return removeFor(options,profileId,{kind:'package',id} as const);}
async function addFor(options:ProfileCollectionReferenceOptions,requestedProfileId:string|undefined,key:SkillCollectionKey):Promise<ProfileCollectionReferenceResult>{assertSafeSkillId(key.id);return withReferenceLock(options,requestedProfileId,key,`bazframe profile ${key.kind==='library'?'libraries':'packages'} add`,async(profileId,directory,path)=>{await assertValidNamespaces(options.bazframeHome,profileId);const existing=await optionalReference(options.bazframeHome,profileId,key);const globalPath=globalCollectionPath(options.bazframeHome,key.kind,key.id);const global=await readCollectionSnapshot(options.bazframeHome,key);await verifySkillSnapshot(options.bazframeHome,global.record.digest);const flat=loadFlatSkillIdentities(await discoverSkillDirectories(join(directory,'skills')));await validateProspectiveSkillCollection(directory,flat,direct(global.record,globalPath));const revalidated=await readCollectionSnapshot(options.bazframeHome,key);if(!sameCollectionSnapshot(global,revalidated))throw new BazframeError('SKILL_COLLECTION_CHANGED',`Global ${key.kind} changed while adding reference: ${key.id}`);if(existing!==undefined){const current=await readProfileCollectionReferenceSnapshot(options.bazframeHome,profileId,key);if(!sameProfileCollectionReferenceSnapshot(existing,current))throw new BazframeError('SKILL_COLLECTION_REFERENCE_CHANGED',`Profile ${key.kind} reference changed while validating: ${path}`);return result(current.reference,profileId,path,'current');}await ensureManagedDirectory(options.bazframeHome,profileCollectionDirectory(options.bazframeHome,profileId,key.kind));const reference:ProfileSkillCollectionReference=key.kind==='library'?{schemaVersion:1,library:key.id}:{schemaVersion:1,package:key.id};if(!await createExclusive(path,encodeProfileCollectionReference(reference),options.bazframeHome,key.kind))throw new BazframeError('SKILL_COLLECTION_REFERENCE_OCCUPIED',`Profile ${key.kind} reference became occupied: ${path}`);return result(reference,profileId,path,'added');});}
async function removeFor(options:ProfileCollectionReferenceOptions,requestedProfileId:string|undefined,key:SkillCollectionKey):Promise<ProfileCollectionReferenceResult>{assertSafeSkillId(key.id);return withReferenceLock(options,requestedProfileId,key,`bazframe profile ${key.kind==='library'?'libraries':'packages'} remove`,async(profileId,_directory,path)=>{const initial=await optionalReference(options.bazframeHome,profileId,key);const empty:ProfileSkillCollectionReference=key.kind==='library'?{schemaVersion:1,library:key.id}:{schemaVersion:1,package:key.id};if(initial===undefined)return result(empty,profileId,path,'absent');const current=await readProfileCollectionReferenceSnapshot(options.bazframeHome,profileId,key);if(!sameProfileCollectionReferenceSnapshot(initial,current))throw new BazframeError('SKILL_COLLECTION_REFERENCE_CHANGED',`Profile ${key.kind} reference changed during removal: ${path}`);const before=await readProfileCollectionReferenceSnapshot(options.bazframeHome,profileId,key);if(!sameProfileCollectionReferenceSnapshot(initial,before))throw new BazframeError('SKILL_COLLECTION_REFERENCE_CHANGED',`Profile ${key.kind} reference changed before removal commit: ${path}`);await unlink(path);await prune(profileCollectionDirectory(options.bazframeHome,profileId,key.kind));return result(initial.reference,profileId,path,'removed');});}
async function withReferenceLock<T>(options:ProfileCollectionReferenceOptions,requestedProfileId:string|undefined,key:SkillCollectionKey,command:string,operation:(profileId:string,directory:string,path:string)=>Promise<T>):Promise<T>{return withStateLock(join(options.bazframeHome,'locks','state.lock'),{command,target:requestedProfileId===undefined?join(options.bazframeHome,'active-profile'):profileDirectory(options.bazframeHome,requestedProfileId)},async()=>{const profileId=requestedProfileId??await readActiveProfile(options.bazframeHome);const directory=profileDirectory(options.bazframeHome,profileId);const path=profileCollectionReferencePath(options.bazframeHome,profileId,key);return withStateLock(join(options.bazframeHome,'locks','profiles',`${profileId}.${key.kind==='library'?'libraries':'packages'}.lock`),{command,target:path},async()=>{const metadata=await lstat(directory);if(metadata.isSymbolicLink()||!metadata.isDirectory())throw new BazframeError('PROFILE_NOT_PHYSICAL',`Profile must be a physical directory: ${directory}`);await readUtf8InstructionFile(join(directory,'AGENTS.md'),`Profile ${JSON.stringify(profileId)} instructions`);const skillMetadata=await lstat(join(directory,'skills'));if(skillMetadata.isSymbolicLink()||!skillMetadata.isDirectory())throw new BazframeError('PROFILE_SKILLS_INVALID',`Profile skills must be a physical directory: ${join(directory,'skills')}`);return operation(profileId,directory,path);},{managedRoot:options.bazframeHome});},{managedRoot:options.bazframeHome});}
async function assertValidNamespaces(home:string,profileId:string):Promise<void>{const namespace=await scanProfileCollectionReferences(home,profileId);if(namespace.diagnostics.length>0)throw new BazframeError('SKILL_COLLECTION_REFERENCE_NAMESPACE_INVALID',`Profile library/package reference namespace is invalid: ${namespace.diagnostics.map(item=>`${item.key.kind}:${item.path}`).join(', ')}`);for(const item of namespace.references)await readProfileCollectionReferenceSnapshot(home,profileId,item.key);}
function direct(record:SkillCollectionRecord,path:string):DirectSkillCollection{return{schemaVersion:1,collectionKind:kindForRecord(record),collectionId:idForRecord(record),collectionRoot:record.root,snapshotDigest:record.digest,skillsRoot:skillsRootForRecord(record),descriptorPath:path,relativeDescriptorPath:`${idForRecord(record)}.json`,preparationState:'ready',rebuildAvailability:'available'};}
async function optionalReference(home:string,profileId:string,key:SkillCollectionKey):Promise<ProfileSkillCollectionReferenceSnapshot|undefined>{try{return await readProfileCollectionReferenceSnapshot(home,profileId,key);}catch(error){if(error instanceof BazframeError&&error.code==='SKILL_COLLECTION_REFERENCE_READ_FAILED'&&error.cause!==undefined&&errorCode(error.cause)==='ENOENT')return undefined;throw error;}}
async function createExclusive(path:string,contents:string,home:string,kind:'library'|'package'):Promise<boolean>{const temporaryDirectory=join(home,'tmp',`${kind}-references`);await ensureManagedDirectory(home,temporaryDirectory);const temporaryPath=join(temporaryDirectory,`${process.pid}.${randomUUID()}.${basename(path)}.tmp`);let handle:FileHandle|undefined;try{handle=await open(temporaryPath,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);await handle.writeFile(contents,'utf8');await handle.sync();await handle.close();handle=undefined;try{await link(temporaryPath,path);return true;}catch(error){if(errorCode(error)==='EEXIST')return false;throw error;}}finally{await handle?.close().catch(()=>undefined);await unlink(temporaryPath).catch(()=>undefined);}}
async function prune(path:string):Promise<void>{try{await rmdir(path);}catch(error){if(!new Set(['ENOENT','ENOTEMPTY','EEXIST']).has(errorCode(error)??''))throw error;}}
function result(reference:ProfileSkillCollectionReference,profileId:string,path:string,action:ProfileCollectionReferenceAction):ProfileCollectionReferenceResult{return{...reference,action,profileId,path};}
