import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import { lstat, open, readdir, type FileHandle } from 'node:fs/promises';
import { join } from 'node:path';
import { BazframeError, errorCode } from '../core/errors.js';
import { collectionKey, type SkillCollectionKey, type SkillCollectionKind } from '../skill-collections/skill-collection-store.js';
import { isSafeSkillId } from '../skills/skill-id.js';
import { isSafeProfileId } from './profile-id.js';
import { profileDirectory } from './profile-store.js';

export type ProfileSkillCollectionReference = { schemaVersion: 1; library: string } | { schemaVersion: 1; package: string };
export interface ProfileSkillCollectionReferencePath { key: SkillCollectionKey; path: string; relativePath: string }
export interface ProfileSkillCollectionReferenceSnapshot { reference: ProfileSkillCollectionReference; path: string; device: bigint; inode: bigint; contentSha256: string }
export interface ProfileSkillCollectionReferenceDiagnostic { key: SkillCollectionKey; path: string }
export interface ProfileSkillCollectionReferenceNamespace {
  references: ProfileSkillCollectionReferencePath[];
  diagnostics: ProfileSkillCollectionReferenceDiagnostic[];
  namespaceIdentities: Readonly<Record<SkillCollectionKind, string>>;
}
export interface ReferencingProfiles { profileIds: string[]; diagnostics: Array<{ profileId: string; diagnostic: ProfileSkillCollectionReferenceDiagnostic }> }
export interface ProfileSkillCollectionReferenceIndex extends ReferencingProfiles { identity: string }
export interface ProfileSkillCollectionReferenceBulkIndex { profileIdsByCollection: ReadonlyMap<string, readonly string[]>; diagnostics: ReferencingProfiles['diagnostics']; identity: string }
export const UNKNOWN_REFERENCE_ID = '<unknown>';

export function idForReference(reference: ProfileSkillCollectionReference): string { return 'library' in reference ? reference.library : reference.package; }
export function kindForReference(reference: ProfileSkillCollectionReference): SkillCollectionKind { return 'library' in reference ? 'library' : 'package'; }
export function profileCollectionDirectory(home:string,profileId:string,kind:SkillCollectionKind):string{return join(profileDirectory(home,profileId),kind==='library'?'libraries':'packages');}
export function profileCollectionReferencePath(home:string,profileId:string,key:SkillCollectionKey):string{return join(profileCollectionDirectory(home,profileId,key.kind),`${key.id}.json`);}
export function encodeProfileCollectionReference(reference:ProfileSkillCollectionReference):string{return `${JSON.stringify('library'in reference?{schemaVersion:1,library:reference.library}:{schemaVersion:1,package:reference.package},null,2)}\n`;}
export function decodeProfileCollectionReference(value:unknown,kind:SkillCollectionKind,expectedId?:string):ProfileSkillCollectionReference{
  if(value===null||typeof value!=='object'||Array.isArray(value))throw invalid(kind,'reference must be a JSON object'); const candidate=value as Record<string,unknown>;
  const expectedKeys=[kind,'schemaVersion'].sort(); const keys=Object.keys(candidate).sort(); if(keys.length!==2||!keys.every((key,index)=>key===expectedKeys[index]))throw invalid(kind,'reference must contain exactly the schema-v1 fields');
  if(candidate.schemaVersion!==1)throw invalid(kind,'unsupported schemaVersion'); const id=candidate[kind]; if(typeof id!=='string'||!isSafeSkillId(id))throw invalid(kind,`${kind} is invalid`); if(expectedId!==undefined&&id!==expectedId)throw invalid(kind,`${kind} does not match reference path`);
  return kind==='library'?{schemaVersion:1,library:id}:{schemaVersion:1,package:id};
}
export async function readProfileCollectionReference(home:string,profileId:string,key:SkillCollectionKey):Promise<ProfileSkillCollectionReference>{return(await readProfileCollectionReferenceSnapshot(home,profileId,key)).reference;}
export async function readProfileCollectionReferenceSnapshot(home:string,profileId:string,key:SkillCollectionKey):Promise<ProfileSkillCollectionReferenceSnapshot>{
  if(!isSafeProfileId(profileId))throw invalid(key.kind,'profile is invalid'); if(!isSafeSkillId(key.id))throw invalid(key.kind,`${key.kind} is invalid`);
  const directoryPaths=[home,join(home,'profiles'),profileDirectory(home,profileId),profileCollectionDirectory(home,profileId,key.kind)]; const path=profileCollectionReferencePath(home,profileId,key); const directories:OpenDirectory[]=[]; let handle:FileHandle|undefined;
  try{
    for(const directoryPath of directoryPaths)directories.push(await openExistingDirectory(directoryPath,'reference ancestor must be a physical directory',key.kind));
    handle=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK); const before=await handle.stat({bigint:true}); if(!before.isFile())throw invalid(key.kind,'reference must be a physical regular file'); const bytes=await handle.readFile(); const after=await handle.stat({bigint:true}); const pathMetadata=await lstat(path,{bigint:true});
    if(!after.isFile()||pathMetadata.isSymbolicLink()||!pathMetadata.isFile()||before.dev!==after.dev||before.ino!==after.ino||after.dev!==pathMetadata.dev||after.ino!==pathMetadata.ino)throw invalid(key.kind,'reference identity changed while reading'); for(const directory of[...directories].reverse())await assertDirectoryStable(directory);
    let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch(error){throw new BazframeError('SKILL_COLLECTION_REFERENCE_INVALID',`Profile ${key.kind} reference is not valid UTF-8.`,{cause:error});} let value:unknown;try{value=JSON.parse(text);}catch(error){throw new BazframeError('SKILL_COLLECTION_REFERENCE_INVALID',`Profile ${key.kind} reference is not valid JSON.`,{cause:error});}
    return{reference:decodeProfileCollectionReference(value,key.kind,key.id),path,device:before.dev,inode:before.ino,contentSha256:createHash('sha256').update(bytes).digest('hex')};
  }catch(error){if(error instanceof BazframeError)throw error;if(errorCode(error)==='ELOOP')throw invalid(key.kind,'reference and its namespace ancestors must be physical');throw new BazframeError('SKILL_COLLECTION_REFERENCE_READ_FAILED',`Could not read profile ${key.kind} reference ${path}${formatCode(error)}`,{cause:error});}
  finally{await handle?.close().catch(()=>undefined);for(const directory of[...directories].reverse())await directory.handle.close().catch(()=>undefined);}
}
export function sameProfileCollectionReferenceSnapshot(a:ProfileSkillCollectionReferenceSnapshot,b:ProfileSkillCollectionReferenceSnapshot):boolean{return a.device===b.device&&a.inode===b.inode&&a.contentSha256===b.contentSha256;}
export async function scanProfileCollectionReferences(home:string,profileId:string):Promise<ProfileSkillCollectionReferenceNamespace>{const[libraries,packages]=await Promise.all([scanReferenceRoot(profileCollectionDirectory(home,profileId,'library'),'library'),scanReferenceRoot(profileCollectionDirectory(home,profileId,'package'),'package')]);return{references:[...libraries.references,...packages.references].sort((a,b)=>compare(collectionKey(a.key.kind,a.key.id),collectionKey(b.key.kind,b.key.id))),diagnostics:[...libraries.diagnostics,...packages.diagnostics],namespaceIdentities:{library:libraries.identity,package:packages.identity}};}
export async function captureProfileCollectionReferenceIndex(home:string,key:SkillCollectionKey):Promise<ProfileSkillCollectionReferenceIndex>{const bulk=await captureProfileCollectionReferenceBulkIndex(home);return{profileIds:[...(bulk.profileIdsByCollection.get(collectionKey(key.kind,key.id))??[])],diagnostics:bulk.diagnostics,identity:bulk.identity};}
export async function findReferencingProfiles(home:string,key:SkillCollectionKey):Promise<ReferencingProfiles>{const{profileIds,diagnostics}=await captureProfileCollectionReferenceIndex(home,key);return{profileIds,diagnostics};}
export async function captureProfileCollectionReferenceBulkIndex(home:string):Promise<ProfileSkillCollectionReferenceBulkIndex>{
  const rootPath=join(home,'profiles');let rootMetadata;try{rootMetadata=await lstat(rootPath,{bigint:true});}catch(error){if(errorCode(error)==='ENOENT')return bulkIndexed(new Map(),[],['profiles:absent']);return invalidProfileBulkIndex();}if(rootMetadata.isSymbolicLink()||!rootMetadata.isDirectory())return invalidProfileBulkIndex();let root:OpenDirectory|undefined;
  try{root=await openDirectory(rootPath,identity(rootMetadata));const names=await enumerateDirectory(root);const profileIdsByCollection=new Map<string,string[]>();const diagnostics:ReferencingProfiles['diagnostics']=[];const identityParts=[`profiles:${identityText(identity(rootMetadata))}`];
    for(const profileId of names){const safe=isSafeProfileId(profileId);const profilePath=join(rootPath,profileId);let metadata;try{metadata=await lstat(profilePath,{bigint:true});}catch{diagnostics.push(indexDiagnostic(safe?profileId:'<unknown-profile>'));identityParts.push(`profile:${profileId}:missing`);continue;}identityParts.push(`profile:${profileId}:${metadata.isSymbolicLink()?'link':metadata.isDirectory()?'directory':'other'}:${identityText(identity(metadata))}`);if(!safe||metadata.isSymbolicLink()||!metadata.isDirectory()){diagnostics.push(indexDiagnostic(safe?profileId:'<unknown-profile>'));continue;}let profile:OpenDirectory|undefined;
      try{profile=await openDirectory(profilePath,identity(metadata));const namespace=await scanProfileCollectionReferences(home,profileId);identityParts.push(`namespace:${profileId}:library:${namespace.namespaceIdentities.library}`,`namespace:${profileId}:package:${namespace.namespaceIdentities.package}`);for(const diagnostic of namespace.diagnostics)diagnostics.push({profileId,diagnostic});for(const path of namespace.references){try{const snapshot=await readProfileCollectionReferenceSnapshot(home,profileId,path.key);identityParts.push(`reference:${profileId}/${path.key.kind}/${path.relativePath}:${snapshot.device}:${snapshot.inode}:${snapshot.contentSha256}`);const key=collectionKey(path.key.kind,path.key.id);const ids=profileIdsByCollection.get(key)??[];ids.push(profileId);profileIdsByCollection.set(key,ids);}catch{diagnostics.push({profileId,diagnostic:diag(path.key.kind,path.key.id,path.relativePath)});identityParts.push(`reference:${profileId}/${path.key.kind}/${path.relativePath}:invalid`);}}await assertDirectoryStable(profile);}catch{diagnostics.push(indexDiagnostic(profileId));identityParts.push(`profile:${profileId}:unstable`);}finally{await profile?.handle.close().catch(()=>undefined);}}
    await assertDirectoryStable(root);return bulkIndexed(profileIdsByCollection,diagnostics,identityParts);
  }catch{return invalidProfileBulkIndex();}finally{await root?.handle.close().catch(()=>undefined);}
}
export function sameProfileCollectionReferenceIndex(a:ProfileSkillCollectionReferenceIndex,b:ProfileSkillCollectionReferenceIndex):boolean{return a.identity===b.identity;}

interface DirectoryIdentity{device:bigint;inode:bigint}interface OpenDirectory{path:string;handle:FileHandle;identity:DirectoryIdentity}
interface ScannedReferenceRoot { references: ProfileSkillCollectionReferencePath[]; diagnostics: ProfileSkillCollectionReferenceDiagnostic[]; identity: string }
async function scanReferenceRoot(rootPath:string,kind:SkillCollectionKind):Promise<ScannedReferenceRoot>{let rootMetadata;try{rootMetadata=await lstat(rootPath,{bigint:true});}catch(error){if(errorCode(error)==='ENOENT')return{references:[],diagnostics:[],identity:'absent'};return invalidRoot(kind);}if(rootMetadata.isSymbolicLink()||!rootMetadata.isDirectory())return invalidRoot(kind);let root:OpenDirectory|undefined;try{root=await openDirectory(rootPath,identity(rootMetadata));const references:ProfileSkillCollectionReferencePath[]=[];const diagnostics:ProfileSkillCollectionReferenceDiagnostic[]=[];for(const name of await enumerateDirectory(root)){const id=idFromName(name);const path=join(rootPath,name);let child;try{child=await lstat(path);}catch{diagnostics.push(diag(kind,id??UNKNOWN_REFERENCE_ID,name));continue;}if(id===undefined||child.isSymbolicLink()||!child.isFile()){diagnostics.push(diag(kind,id??UNKNOWN_REFERENCE_ID,name));continue;}references.push({key:{kind,id},path,relativePath:name});}await assertDirectoryStable(root);return{references,diagnostics,identity:identityText(root.identity)};}catch{return invalidRoot(kind);}finally{await root?.handle.close().catch(()=>undefined);}}
async function openExistingDirectory(path:string,detail:string,kind:SkillCollectionKind):Promise<OpenDirectory>{const metadata=await lstat(path,{bigint:true});if(metadata.isSymbolicLink()||!metadata.isDirectory())throw invalid(kind,detail);return openDirectory(path,identity(metadata));}
async function openDirectory(path:string,expected:DirectoryIdentity):Promise<OpenDirectory>{const handle=await open(path,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);try{const opened=await handle.stat({bigint:true});if(!opened.isDirectory()||!sameIdentity(identity(opened),expected))throw new Error('directory identity changed');const directory={path,handle,identity:expected};await assertDirectoryStable(directory);return directory;}catch(error){await handle.close().catch(()=>undefined);throw error;}}
async function enumerateDirectory(directory:OpenDirectory):Promise<string[]>{await assertDirectoryStable(directory);const names=(await readdir(directory.path)).sort(compare);await assertDirectoryStable(directory);return names;}
async function assertDirectoryStable(directory:OpenDirectory):Promise<void>{const[opened,current]=await Promise.all([directory.handle.stat({bigint:true}),lstat(directory.path,{bigint:true})]);if(!opened.isDirectory()||current.isSymbolicLink()||!current.isDirectory()||!sameIdentity(identity(opened),directory.identity)||!sameIdentity(identity(current),directory.identity))throw new Error('directory identity changed');}
function identity(metadata:{dev:bigint;ino:bigint}):DirectoryIdentity{return{device:metadata.dev,inode:metadata.ino};}function sameIdentity(a:DirectoryIdentity,b:DirectoryIdentity):boolean{return a.device===b.device&&a.inode===b.inode;}function idFromName(name:string):string|undefined{if(!name.endsWith('.json'))return undefined;const id=name.slice(0,-5);return isSafeSkillId(id)?id:undefined;}
function bulkIndexed(map:Map<string,string[]>,diagnostics:ReferencingProfiles['diagnostics'],identityParts:string[]):ProfileSkillCollectionReferenceBulkIndex{const sortedDiagnostics=[...diagnostics].sort((a,b)=>compare(`${a.profileId}\0${collectionKey(a.diagnostic.key.kind,a.diagnostic.key.id)}\0${a.diagnostic.path}`,`${b.profileId}\0${collectionKey(b.diagnostic.key.kind,b.diagnostic.key.id)}\0${b.diagnostic.path}`));const sortedMap=new Map([...map.entries()].sort(([a],[b])=>compare(a,b)).map(([key,ids])=>[key,[...new Set(ids)].sort(compare)]as const));const material=[...identityParts.sort(compare),...sortedDiagnostics.map(item=>`diagnostic:${item.profileId}:${collectionKey(item.diagnostic.key.kind,item.diagnostic.key.id)}:${item.diagnostic.path}`)].join('\n');return{profileIdsByCollection:sortedMap,diagnostics:sortedDiagnostics,identity:createHash('sha256').update(material).digest('hex')};}
function invalidProfileBulkIndex():ProfileSkillCollectionReferenceBulkIndex{return bulkIndexed(new Map(),[indexDiagnostic('<unknown-profile>')],['profiles:invalid']);}function identityText(value:DirectoryIdentity):string{return`${value.device}:${value.inode}`;}function indexDiagnostic(profileId:string):ReferencingProfiles['diagnostics'][number]{return{profileId,diagnostic:diag('library',UNKNOWN_REFERENCE_ID,'.')};}function invalidRoot(kind:SkillCollectionKind):ScannedReferenceRoot{return{references:[],diagnostics:[diag(kind,UNKNOWN_REFERENCE_ID,'.')],identity:'invalid'};}function diag(kind:SkillCollectionKind,id:string,path:string):ProfileSkillCollectionReferenceDiagnostic{return{key:{kind,id},path};}function invalid(kind:SkillCollectionKind,detail:string):BazframeError{return new BazframeError('SKILL_COLLECTION_REFERENCE_INVALID',`Invalid profile ${kind} reference: ${detail}.`);}function formatCode(error:unknown):string{const code=errorCode(error);return code===undefined?'':` (${code})`;}function compare(a:string,b:string):number{return a<b?-1:a>b?1:0;}
