import { mkdtemp, mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { runCli } from '../../../src/cli/run-cli.js';

const roots:string[]=[];const execFileAsync=promisify(execFile);
afterEach(async()=>{await Promise.all(roots.splice(0).map((root)=>rm(root,{recursive:true,force:true})));});
async function invoke(argv:string[], overrides:Record<string,unknown>={}){const root=await mkdtemp(join(tmpdir(),'bazframe-json-'));roots.push(root);return invokeAt(root,argv,overrides);}
async function invokeAt(root:string,argv:string[],overrides:Record<string,unknown>={}){
 let stdout='',stderr='';
 const status=await runCli(argv,{environment:{...process.env,BAZFRAME_HOME:join(root,'home'),PI_CODING_AGENT_DIR:join(root,'pi'),NO_COLOR:'1'},userHome:root,writeStdout:(text)=>{stdout+=text;},writeStderr:(text)=>{stderr+=text;},...overrides});
 expect(stdout.endsWith('\n')).toBe(true);expect(stdout.trim().split('\n')).toHaveLength(1);
 return{status,stdout,stderr,root,document:JSON.parse(stdout) as Record<string,unknown>};
}
describe('CLI JSON protocol',()=>{
 it('emits one schema-v1 success document',async()=>{const result=await invoke(['profile','list','--json']);expect(result).toMatchObject({status:0,stderr:'',document:{schemaVersion:1,ok:true,command:'profile.list',diagnostics:[]}});expect(result.document.result).toMatchObject({profiles:[],active:{state:'unselected'}});});
 it('projects every supported query family from structured state',async()=>{const created=await invoke(['profile','add','--json','focused']);const root=created.root;await invokeAt(root,['profile','use','--json','focused']);for(const [argv,command] of [[['profile','list','--json'],'profile.list'],[['profile','current','--json'],'profile.current'],[['skill','list','--json'],'skill.list'],[['library','list','--json'],'library.list'],[['package','list','--json'],'package.list'],[['profile','skill','list','--json'],'profile.skill.list'],[['profile','library','list','--json'],'profile.library.list'],[['profile','package','list','--json'],'profile.package.list'],[['project','list','--json'],'project.list'],[['global','show','--json'],'global.show'],[['adapter','list','--json'],'adapter.list']] as const){const result=await invokeAt(root,[...argv]);expect(result.document).toMatchObject({schemaVersion:1,ok:true,command});}const global=await invokeAt(root,['global','show','--json']);expect(global.document).toMatchObject({result:{policy:'enabled',statePath:null}});});
 it('reports active and explicit nested mutation targets directly',async()=>{const created=await invoke(['profile','add','--json','focused']);const root=created.root;await invokeAt(root,['profile','add','--json','reviewer']);await invokeAt(root,['profile','use','--json','focused']);const source=join(root,'demo');await mkdir(source,{recursive:true});await writeFile(join(source,'SKILL.md'),'---\nname: demo\ndescription: Demo.\n---\n');await invokeAt(root,['skill','add','--json',source]);const active=await invokeAt(root,['profile','skill','add','--json','demo']);expect(active.document).toMatchObject({result:{profileTarget:{id:'focused',source:'active-selection'},skillId:'demo'}});const explicit=await invokeAt(root,['profile','skill','add','--profile=reviewer','--json','demo']);expect(explicit.document).toMatchObject({result:{profileTarget:{id:'reviewer',source:'explicit'},skillId:'demo'}});});
 it('uses stable operational codes for policy enable failures',async()=>{const global=await invoke(['global','enable','--json']);expect(global.document).toMatchObject({ok:false,error:{category:'operational',code:'PI_ADAPTER_NOT_READY'}});const root=global.root,repository=join(root,'repo');await mkdir(repository);await execFileAsync('git',['init','--quiet',repository]);const project=await invokeAt(root,['project','enable','--json'],{cwd:()=>repository});expect(project.document).toMatchObject({ok:false,error:{category:'operational',code:'PI_ADAPTER_NOT_READY'}});});
 it('maps status through the stable DTO without internal provider or loader fields',async()=>{const result=await invoke(['status','--json']);const text=JSON.stringify(result.document);expect(result.document).toMatchObject({result:{health:'attention',globalPolicy:{policy:'enabled',statePath:null},managedProviders:[],correctiveActions:expect.any(Array)}});for(const forbidden of ['fetchUrl','transport','loaded','schemaVersion\\":1,\\"kind'])expect(text).not.toContain(forbidden);});
 it('emits usage and migration documents on stdout',async()=>{const usage=await invoke(['profile','remove','--json']);expect(usage).toMatchObject({status:2,stderr:'',document:{ok:false,error:{code:'CLI_USAGE',category:'usage'}}});const migration=await invoke(['--json','profiles']);expect(migration).toMatchObject({status:2,stderr:'',document:{ok:false,error:{code:'CLI_MIGRATION_REQUIRED',category:'migration'}}});});
 it('normalizes operational and unexpected errors',async()=>{const operational=await invoke(['profile','current','--json']);expect(operational.document).toMatchObject({ok:false,error:{category:'operational',code:'NO_ACTIVE_PROFILE'}});const cwd=vi.fn(()=>{throw new Error('secret stack detail');});const unexpected=await invoke(['project','list','--json'],{cwd});expect(unexpected.document).toMatchObject({ok:false,error:{category:'internal',code:'INTERNAL_ERROR',message:'Bazframe encountered an unexpected internal error.'}});expect(unexpected.stdout).not.toContain('secret');});
 it('keeps status attention ok with exit 3',async()=>{const result=await invoke(['status','--json']);expect(result).toMatchObject({status:3,stderr:'',document:{ok:true,command:'status',result:{health:'attention'}}});});
 it('rejects interactive JSON without launching side effects',async()=>{const launchTui=vi.fn();const result=await invoke(['tui','--json'],{launchTui});expect(result.document).toMatchObject({ok:false,error:{code:'CLI_JSON_UNSUPPORTED'}});expect(launchTui).not.toHaveBeenCalled();});
 it('requires --yes before managed package acquisition',async()=>{const confirmManagedGitPackageBuild=vi.fn();const result=await invoke(['package','add','git:owner/pkg','--json'],{confirmManagedGitPackageBuild});expect(result.document).toMatchObject({ok:false,error:{code:'MANAGED_GIT_BUILD_CONFIRMATION_REQUIRED'}});expect(confirmManagedGitPackageBuild).not.toHaveBeenCalled();await expect(stat(join(result.root,'home'))).rejects.toMatchObject({code:'ENOENT'});});
});
