import{link,mkdtemp,mkdir,readFile,realpath,rename,unlink,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{describe,expect,it}from'vitest';
import{addLibrary,addPackage,buildPackage,removeLibrary,removePackage,updateLibrary}from'../../../src/skill-collections/skill-collection-lifecycle.js';
import{addProfile}from'../../../src/profiles/profile-management.js';
import{addProfileLibraryReference,addProfilePackageReference,removeProfileLibraryReference,removeProfilePackageReference}from'../../../src/profiles/profile-skill-collection-reference-lifecycle.js';
import{encodeProfileCollectionReference}from'../../../src/profiles/profile-skill-collection-reference.js';import{readLibrary,readPackage}from'../../../src/skill-collections/skill-collection-store.js';import{verifySkillSnapshot}from'../../../src/skill-collections/skill-snapshot.js';
import{prepareLibrary}from'../../../src/skill-collections/skill-collection-preparation.js';
const skill=(name:string)=>`---\nname: ${name}\ndescription: A useful Skill\n---\n# ${name}\n`;
async function setup(){const temp=await mkdtemp(join(tmpdir(),'bazframe-life-'));const home=join(temp,'home');await mkdir(home);return{temp,home};}
describe('library and package lifecycle',()=>{
 it('adds and updates a library without executing provider code',async()=>{const{temp,home}=await setup();const root=join(temp,'library');await mkdir(join(root,'one'),{recursive:true});await writeFile(join(root,'one','SKILL.md'),skill('one'));const marker=join(temp,'marker');await writeFile(join(root,'bazframe-source.json'),JSON.stringify({build:[process.execPath,'-e',`require('fs').writeFileSync(${JSON.stringify(marker)},'ran')`]}));const added=await addLibrary({bazframeHome:home},root);expect('library'in added&&added.library).toBe('library');await expect(readFile(marker)).rejects.toThrow();await writeFile(join(root,'one','note'),'changed');await updateLibrary({bazframeHome:home},'library');expect((await readLibrary(home,'library')).digest).not.toBe(added.digest);await expect(readFile(marker)).rejects.toThrow();});
 it('explicitly builds a package with literal argv, cwd, environment, and complete artifact retention',async()=>{const{temp,home}=await setup();const root=join(temp,'package');await mkdir(root);const script=`const fs=require('fs');fs.mkdirSync('dist/skills/inside',{recursive:true});fs.mkdirSync('dist/shared',{recursive:true});fs.writeFileSync('dist/skills/inside/SKILL.md',${JSON.stringify(skill('inside'))});fs.writeFileSync('dist/shared/data',process.cwd()+'\\n'+process.env.BAZFRAME_PACKAGE_PROBE+'\\n'+process.argv[1])`;await writeFile(join(root,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',script,'literal argument'],artifactRoot:'dist',skillsRoot:'skills'}));const added=await addPackage({bazframeHome:home,environment:{...process.env,BAZFRAME_PACKAGE_PROBE:'environment'}},root);expect('package'in added&&added.package).toBe('package');const record=await readPackage(home,'package');expect(record.skillsRoot).toBe('skills');const snapshot=await verifySkillSnapshot(home,record.digest);expect(await readFile(join(snapshot.artifactPath,'shared','data'),'utf8')).toBe(`${await realpath(root)}\nenvironment\nliteral argument`);});
 it('allows a library and package with the same basename',async()=>{const{temp,home}=await setup();const library=join(temp,'a','toolkit');const pkg=join(temp,'b','toolkit');await mkdir(library,{recursive:true});await mkdir(pkg,{recursive:true});await writeFile(join(pkg,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',"require('fs').mkdirSync('dist/skills',{recursive:true})"],artifactRoot:'dist',skillsRoot:'skills'}));await addLibrary({bazframeHome:home},library);await addPackage({bazframeHome:home},pkg);expect((await readLibrary(home,'toolkit')).library).toBe('toolkit');expect((await readPackage(home,'toolkit')).package).toBe('toolkit');});
 it('wraps package spawn failure and publishes no record',async()=>{const{temp,home}=await setup();const root=join(temp,'missing-builder');await mkdir(root);await writeFile(join(root,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[join(temp,'does-not-exist')],artifactRoot:'.',skillsRoot:'.'}));await expect(addPackage({bazframeHome:home},root)).rejects.toMatchObject({code:'PACKAGE_BUILD_FAILED'});await expect(readPackage(home,'missing-builder')).rejects.toBeDefined();});
 it('preserves the active package record when a later build fails',async()=>{const{temp,home}=await setup();const root=join(temp,'durable-package');await mkdir(root);const marker=join(root,'fail');const script=`const fs=require('fs');if(fs.existsSync('fail'))process.exit(7);fs.mkdirSync('dist/skills',{recursive:true});fs.writeFileSync('dist/shared.txt','ok')`;await writeFile(join(root,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',script],artifactRoot:'dist',skillsRoot:'skills'}));await addPackage({bazframeHome:home},root);const before=await readPackage(home,'durable-package');await writeFile(marker,'fail');await expect(buildPackage({bazframeHome:home},'durable-package')).rejects.toThrow(/status 7/);expect((await readPackage(home,'durable-package')).digest).toBe(before.digest);});
 it('rejects a package manifest at a library root without running it',async()=>{const{temp,home}=await setup();const root=join(temp,'prepared');await mkdir(root);await writeFile(join(root,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e','process.exit(0)'],artifactRoot:'.',skillsRoot:'.'}));await expect(addLibrary({bazframeHome:home},root)).rejects.toThrow(/package add/);});
 it('preserves the active library record when update validation fails',async()=>{const{temp,home}=await setup();const root=join(temp,'stable');await mkdir(join(root,'ok'),{recursive:true});await writeFile(join(root,'ok','SKILL.md'),skill('ok'));await addLibrary({bazframeHome:home},root);const before=await readLibrary(home,'stable');await writeFile(join(root,'ok','SKILL.md'),'---\nname: ok\n---\n');await expect(updateLibrary({bazframeHome:home},'stable')).rejects.toThrow(/description is required/);expect((await readLibrary(home,'stable')).digest).toBe(before.digest);});

 it('keeps reference add idempotent while revalidating and removes absent references without a global target',async()=>{const{temp,home}=await setup();await addProfile(home,'focused');const root=join(temp,'referenced');await mkdir(join(root,'alpha'),{recursive:true});await writeFile(join(root,'alpha','SKILL.md'),skill('alpha'));await addLibrary({bazframeHome:home},root);await expect(addProfileLibraryReference({bazframeHome:home},'focused','referenced')).resolves.toMatchObject({action:'added'});await expect(addProfileLibraryReference({bazframeHome:home},'focused','referenced')).resolves.toMatchObject({action:'current'});await mkdir(join(home,'profiles','focused','skills','alpha'),{recursive:true});await writeFile(join(home,'profiles','focused','skills','alpha','SKILL.md'),skill('alpha'));await expect(addProfileLibraryReference({bazframeHome:home},'focused','referenced')).rejects.toMatchObject({code:'SKILL_COLLECTION_CANDIDATE_DUPLICATE'});await expect(removeProfilePackageReference({bazframeHome:home},'focused','missing')).resolves.toMatchObject({action:'absent'});});

 it('records canonical singular profile-reference lock commands',async()=>{const{temp,home}=await setup();await addProfile(home,'focused');const root=join(temp,'lock-library');await mkdir(root);await addLibrary({bazframeHome:home},root);let command='';await addProfileLibraryReference({bazframeHome:home,testHooks:{afterStateLockAcquired:async()=>{command=JSON.parse(await readFile(join(home,'locks','state.lock'),'utf8')).command;}}},'focused','lock-library');expect(command).toBe('bazframe profile library add');});

 it('rejects a conflicting package build in any dependent profile and preserves the active digest',async()=>{const{temp,home}=await setup();await addProfile(home,'focused');await addProfile(home,'reviewer');const root=join(temp,'dependent-package');await mkdir(root);await writeFile(join(root,'name.txt'),'alpha\n');const script="const fs=require('fs');const name=fs.readFileSync('name.txt','utf8').trim();fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/skills/item',{recursive:true});fs.writeFileSync('dist/skills/item/SKILL.md','---\\nname: '+name+'\\ndescription: '+name+'\\n---\\n# '+name+'\\n')";await writeFile(join(root,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',script],artifactRoot:'dist',skillsRoot:'skills'}));await addPackage({bazframeHome:home},root);await addProfilePackageReference({bazframeHome:home},'focused','dependent-package');await addProfilePackageReference({bazframeHome:home},'reviewer','dependent-package');await mkdir(join(home,'profiles','reviewer','skills','beta'),{recursive:true});await writeFile(join(home,'profiles','reviewer','skills','beta','SKILL.md'),skill('beta'));const before=await readPackage(home,'dependent-package');await writeFile(join(root,'name.txt'),'beta\n');await expect(buildPackage({bazframeHome:home},'dependent-package')).rejects.toMatchObject({code:'SKILL_COLLECTION_DEPENDENT_INVALID'});expect((await readPackage(home,'dependent-package')).digest).toBe(before.digest);});

 it('validates every dependent and refuses referenced library and package removal',async()=>{const{temp,home}=await setup();await addProfile(home,'focused');await addProfile(home,'reviewer');const library=join(temp,'shared');await mkdir(join(library,'alpha'),{recursive:true});await writeFile(join(library,'alpha','SKILL.md'),skill('alpha'));await addLibrary({bazframeHome:home},library);await addProfileLibraryReference({bazframeHome:home},'focused','shared');await addProfileLibraryReference({bazframeHome:home},'reviewer','shared');await mkdir(join(home,'profiles','reviewer','skills','beta'),{recursive:true});await writeFile(join(home,'profiles','reviewer','skills','beta','SKILL.md'),skill('beta'));await mkdir(join(library,'beta'));await writeFile(join(library,'beta','SKILL.md'),skill('beta'));const before=await readLibrary(home,'shared');await expect(updateLibrary({bazframeHome:home},'shared')).rejects.toMatchObject({code:'SKILL_COLLECTION_DEPENDENT_INVALID'});expect((await readLibrary(home,'shared')).digest).toBe(before.digest);await expect(removeLibrary({bazframeHome:home},'shared')).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCED'});await removeProfileLibraryReference({bazframeHome:home},'focused','shared');await removeProfileLibraryReference({bazframeHome:home},'reviewer','shared');await expect(removeLibrary({bazframeHome:home},'shared')).resolves.toMatchObject({action:'removed'});
 const pkg=join(temp,'removable');await mkdir(pkg);await writeFile(join(pkg,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',"require('fs').mkdirSync('dist/skills',{recursive:true})"],artifactRoot:'dist',skillsRoot:'skills'}));await addPackage({bazframeHome:home},pkg);await addProfilePackageReference({bazframeHome:home},'focused','removable');await expect(removePackage({bazframeHome:home},'removable')).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCED'});await removeProfilePackageReference({bazframeHome:home},'focused','removable');await expect(removePackage({bazframeHome:home},'removable')).resolves.toMatchObject({action:'removed'});});

 it('revalidates the complete typed reference index before add, update, build, and remove commits',async()=>{const{temp,home}=await setup();await addProfile(home,'focused');const library=join(temp,'library-race');await mkdir(library);const libraryRef=join(home,'profiles','focused','libraries','library-race.json');const libraryBytes=encodeProfileCollectionReference({schemaVersion:1,library:'library-race'});await expect(addLibrary({bazframeHome:home},library,{beforeReferenceIndexRevalidation:async()=>{await mkdir(join(home,'profiles','focused','libraries'),{recursive:true});await writeFile(libraryRef,libraryBytes);}})).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCE_INDEX_CHANGED'});await unlink(libraryRef);await addLibrary({bazframeHome:home},library);await writeFile(libraryRef,libraryBytes);const before=await readLibrary(home,'library-race');await expect(updateLibrary({bazframeHome:home},'library-race',{beforeReferenceIndexRevalidation:async()=>{await writeFile(libraryRef,'{}\n');}})).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCE_INDEX_CHANGED'});expect((await readLibrary(home,'library-race')).digest).toBe(before.digest);await unlink(libraryRef);await expect(removeLibrary({bazframeHome:home},'library-race',{beforeReferenceIndexRevalidation:async()=>{await writeFile(libraryRef,libraryBytes);}})).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCE_INDEX_CHANGED'});
 const pkg=join(temp,'package-race');await mkdir(pkg);await writeFile(join(pkg,'bazframe-package.json'),JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',"require('fs').mkdirSync('dist/skills',{recursive:true})"],artifactRoot:'dist',skillsRoot:'skills'}));await addPackage({bazframeHome:home},pkg);const packageRef=join(home,'profiles','focused','packages','package-race.json');await expect(buildPackage({bazframeHome:home},'package-race',{beforeReferenceIndexRevalidation:async()=>{await mkdir(join(home,'profiles','focused','packages'),{recursive:true});await writeFile(packageRef,encodeProfileCollectionReference({schemaVersion:1,package:'package-race'}));}})).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCE_INDEX_CHANGED'});});

 it('revalidates package manifest identity/content at add and build commit boundaries',async()=>{const{temp,home}=await setup();const root=join(temp,'manifest-race');await mkdir(root);const manifest=join(root,'bazframe-package.json');const value=(skillsRoot:string)=>JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',"require('fs').mkdirSync('dist/skills',{recursive:true})"],artifactRoot:'dist',skillsRoot});await writeFile(manifest,value('skills'));await expect(addPackage({bazframeHome:home},root,{beforeReferenceIndexRevalidation:async()=>{await writeFile(manifest,value('.'));}})).rejects.toMatchObject({code:'PACKAGE_MANIFEST_CHANGED'});await writeFile(manifest,value('skills'));const added=await addPackage({bazframeHome:home},root);await expect(buildPackage({bazframeHome:home},'manifest-race',{beforeReferenceIndexRevalidation:async()=>{await writeFile(manifest,value('.'));}})).rejects.toMatchObject({code:'PACKAGE_MANIFEST_CHANGED'});expect((await readPackage(home,'manifest-race')).digest).toBe(added.digest);});

 it('rejects a library that crosses the package boundary while its snapshot is staged',async()=>{const{temp,home}=await setup();const root=join(temp,'snapshot-boundary');await mkdir(root);const manifest=join(root,'bazframe-package.json');await expect(prepareLibrary(home,root,{beforePublish:async()=>{await writeFile(manifest,JSON.stringify({schemaVersion:1,build:['true'],artifactRoot:'.',skillsRoot:'.'}));}})).rejects.toMatchObject({code:'LIBRARY_IS_PACKAGE'});});

 it('revalidates package-manifest absence at library add and update commit boundaries',async()=>{const{temp,home}=await setup();const root=join(temp,'library-boundary');await mkdir(root);const manifest=join(root,'bazframe-package.json');const bytes=JSON.stringify({schemaVersion:1,build:['true'],artifactRoot:'.',skillsRoot:'.'});await expect(addLibrary({bazframeHome:home},root,{beforeReferenceIndexRevalidation:async()=>{await writeFile(manifest,bytes);}})).rejects.toMatchObject({code:'LIBRARY_IS_PACKAGE'});await unlink(manifest);const added=await addLibrary({bazframeHome:home},root);await expect(updateLibrary({bazframeHome:home},'library-boundary',{beforeReferenceIndexRevalidation:async()=>{await writeFile(manifest,bytes);}})).rejects.toMatchObject({code:'LIBRARY_IS_PACKAGE'});expect((await readLibrary(home,'library-boundary')).digest).toBe(added.digest);});

 it('rejects provider-root substitution after final reference-index revalidation for library add and update',async()=>{const{temp,home}=await setup();const addRoot=join(temp,'library-add-substitution');await mkdir(addRoot);await expect(addLibrary({bazframeHome:home},addRoot,{beforeReferenceIndexRevalidation:async()=>{await rename(addRoot,`${addRoot}-old`);await mkdir(addRoot);}})).rejects.toMatchObject({code:'SKILL_COLLECTION_ROOT_CHANGED'});await expect(readLibrary(home,'library-add-substitution')).rejects.toBeDefined();
 const updateRoot=join(temp,'library-update-substitution');await mkdir(updateRoot);const added=await addLibrary({bazframeHome:home},updateRoot);await expect(updateLibrary({bazframeHome:home},'library-update-substitution',{beforeReferenceIndexRevalidation:async()=>{await rename(updateRoot,`${updateRoot}-old`);await mkdir(updateRoot);}})).rejects.toMatchObject({code:'SKILL_COLLECTION_ROOT_CHANGED'});expect((await readLibrary(home,'library-update-substitution')).digest).toBe(added.digest);});

 it('rejects package add and build root substitution even when the unchanged manifest is hard-linked into the replacement',async()=>{const{temp,home}=await setup();const manifestBytes=JSON.stringify({schemaVersion:1,build:[process.execPath,'-e',"require('fs').mkdirSync('dist/skills',{recursive:true})"],artifactRoot:'dist',skillsRoot:'skills'});const substitute=async(root:string)=>{const old=`${root}-old`;await rename(root,old);await mkdir(root);await link(join(old,'bazframe-package.json'),join(root,'bazframe-package.json'));};
 const addRoot=join(temp,'package-add-substitution');await mkdir(addRoot);await writeFile(join(addRoot,'bazframe-package.json'),manifestBytes);await expect(addPackage({bazframeHome:home},addRoot,{beforeReferenceIndexRevalidation:()=>substitute(addRoot)})).rejects.toMatchObject({code:'SKILL_COLLECTION_ROOT_CHANGED'});await expect(readPackage(home,'package-add-substitution')).rejects.toBeDefined();
 const buildRoot=join(temp,'package-build-substitution');await mkdir(buildRoot);await writeFile(join(buildRoot,'bazframe-package.json'),manifestBytes);const added=await addPackage({bazframeHome:home},buildRoot);await expect(buildPackage({bazframeHome:home},'package-build-substitution',{beforeReferenceIndexRevalidation:()=>substitute(buildRoot)})).rejects.toMatchObject({code:'SKILL_COLLECTION_ROOT_CHANGED'});expect((await readPackage(home,'package-build-substitution')).digest).toBe(added.digest);});

 it('treats empty typed namespace creation and replacement as activation and removal races',async()=>{const{temp,home}=await setup();await addProfile(home,'focused');const activationRoot=join(temp,'namespace-activation');await mkdir(activationRoot);await expect(addLibrary({bazframeHome:home},activationRoot,{beforeReferenceIndexRevalidation:async()=>{await mkdir(join(home,'profiles','focused','libraries'));}})).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCE_INDEX_CHANGED'});await expect(readLibrary(home,'namespace-activation')).rejects.toBeDefined();
 const removalRoot=join(temp,'namespace-removal');await mkdir(removalRoot);await addLibrary({bazframeHome:home},removalRoot);const namespace=join(home,'profiles','focused','packages');await mkdir(namespace);await expect(removeLibrary({bazframeHome:home},'namespace-removal',{beforeReferenceIndexRevalidation:async()=>{await rename(namespace,`${namespace}-old`);await mkdir(namespace);}})).rejects.toMatchObject({code:'SKILL_COLLECTION_REFERENCE_INDEX_CHANGED'});await expect(readLibrary(home,'namespace-removal')).resolves.toMatchObject({library:'namespace-removal'});});
});
