import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, mkdtemp, rm, symlink, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { decodePackageManifest, readPackageManifest, samePackageManifestSnapshot } from '../../../src/packages/package-manifest.js';
const execFileAsync = promisify(execFile);

describe('package manifest',()=>{
  it('accepts the exact schema',()=>{expect(decodePackageManifest({schemaVersion:1,build:['npm','run','build'],artifactRoot:'dist',skillsRoot:'skills'})).toEqual({schemaVersion:1,build:['npm','run','build'],artifactRoot:'dist',skillsRoot:'skills'});});
  it('rejects old and extra fields',()=>{expect(()=>decodePackageManifest({schemaVersion:1,build:['x'],artifactRoot:'.',sourceUnitRoot:'.'})).toThrow(/exactly/);expect(()=>decodePackageManifest({schemaVersion:1,build:['x'],artifactRoot:'.',skillsRoot:'.',extra:true})).toThrow(/exactly/);});
  it('rejects escaping roots, nonliteral paths, and invalid argv',()=>{expect(()=>decodePackageManifest({schemaVersion:1,build:[],artifactRoot:'.',skillsRoot:'.'})).toThrow(/nonempty/);expect(()=>decodePackageManifest({schemaVersion:1,build:['x'],artifactRoot:'../dist',skillsRoot:'.'})).toThrow(/artifactRoot/);expect(()=>decodePackageManifest({schemaVersion:1,build:['x'],artifactRoot:'dist\\out',skillsRoot:'.'})).toThrow(/artifactRoot/);expect(()=>decodePackageManifest({schemaVersion:1,build:[''],artifactRoot:'.',skillsRoot:'.'})).toThrow(/nonempty/);expect(()=>decodePackageManifest({schemaVersion:1,build:['x'],artifactRoot:'.',skillsRoot:'/skills'})).toThrow(/skillsRoot/);});
  it('requires a physical bazframe-package.json',async()=>{const root=await mkdtemp(join(tmpdir(),'bazframe-package-'));await expect(readPackageManifest(root)).rejects.toThrow(/bazframe-package\.json/);await writeFile(join(root,'target.json'),JSON.stringify({schemaVersion:1,build:['x'],artifactRoot:'.',skillsRoot:'.'}));await symlink(join(root,'target.json'),join(root,'bazframe-package.json'));await expect(readPackageManifest(root)).rejects.toThrow(/physical/);});
  it('rejects fatal UTF-8, directories, FIFO and other non-regular manifests without blocking',async()=>{const root=await mkdtemp(join(tmpdir(),'bazframe-package-special-'));const path=join(root,'bazframe-package.json');await writeFile(path,new Uint8Array([0xff]));await expect(readPackageManifest(root)).rejects.toThrow(/UTF-8/);await unlink(path);await mkdir(path);await expect(readPackageManifest(root)).rejects.toThrow(/regular file/);if(process.platform!=='win32'){await rm(path,{recursive:true});await execFileAsync('mkfifo',[path]);await expect(readPackageManifest(root)).rejects.toThrow(/regular file/);}});
  it('captures stable manifest identity and content for commit-boundary comparison',async()=>{const root=await mkdtemp(join(tmpdir(),'bazframe-package-stable-'));const path=join(root,'bazframe-package.json');const firstBytes=JSON.stringify({schemaVersion:1,build:['x'],artifactRoot:'.',skillsRoot:'.'});await writeFile(path,firstBytes);const first=await readPackageManifest(root);const same=await readPackageManifest(root);expect(samePackageManifestSnapshot(first,same)).toBe(true);await unlink(path);await writeFile(path,JSON.stringify({schemaVersion:1,build:['x'],artifactRoot:'dist',skillsRoot:'.'}));const replaced=await readPackageManifest(root);expect(samePackageManifestSnapshot(first,replaced)).toBe(false);});
});
