//! Opt-in W0 correction regression, NOT the historical reproducer or cause attribution.
//! The supplied parent must be a NEW disposable private physical local-NTFS directory.
//! No fixture is removed, including on failure; a second invocation needs a new parent.

use super::*;
use crate::read_change::security_fields;
use std::cell::RefCell;
use std::rc::Rc;
use windows_sys::Win32::Storage::FileSystem::{
    FILE_WRITE_ATTRIBUTES, SetFileInformationByHandle, WriteFile,
};

// Fixture-only ACL evidence uses explicitly authorized descriptor handles, never
// the ordinary path observation contract exercised by the admission seam.
struct FixtureInspection {
    physical: WindowsPathInspection,
    security: WindowsSecurityObservation,
}
impl std::ops::Deref for FixtureInspection {
    type Target = WindowsPathInspection;
    fn deref(&self) -> &Self::Target {
        &self.physical
    }
}
fn fixture_opened(opened: &OpenedPath) -> NativeResult<FixtureInspection> {
    Ok(FixtureInspection {
        physical: inspect_opened_path(opened)?,
        security: inspect_security(opened.handle.0)?,
    })
}
fn fixture_path(path: &str) -> NativeResult<FixtureInspection> {
    fixture_opened(&open_admitted_path(
        path,
        FILE_READ_ATTRIBUTES | READ_CONTROL,
    )?)
}

type Hook = Box<dyn FnOnce(&[AdmissionPrefixObservation])>;
type ReopenedHook =
    Box<dyn FnMut(usize, &AdmissionPrefixObservation, &str, &WindowsObjectObservation)>;
type InspectionHook = Box<dyn FnOnce()>;
type TestResult<T> = Result<T, &'static str>;

thread_local! {
    // Thread-local rather than global: parallel tests cannot consume this hook. Taking it
    // before invocation also prevents protected-creation helpers from recursively firing it.
    static AFTER_OBSERVATIONS: RefCell<Option<Hook>> = RefCell::new(None);
    static AT_REOPENED: RefCell<Option<ReopenedHook>> = RefCell::new(None);
    static DURING_INSPECTION: RefCell<Option<InspectionHook>> = RefCell::new(None);
    static CONTENT_SEAM: RefCell<Option<(&'static str, InspectionHook)>> = RefCell::new(None);
}

pub(super) fn after_initial_observations(observations: &[AdmissionPrefixObservation]) {
    let hook = AFTER_OBSERVATIONS.with(|slot| slot.borrow_mut().take());
    if let Some(hook) = hook {
        hook(observations);
    }
}

pub(super) fn at_reopened_observation(
    index: usize,
    initial: &AdmissionPrefixObservation,
    canonical_path: &str,
    object: &WindowsObjectObservation,
) {
    AT_REOPENED.with(|slot| {
        if let Some(hook) = slot.borrow_mut().as_mut() {
            hook(index, initial, canonical_path, object);
        }
    });
}

pub(super) fn during_opened_inspection() {
    let hook = DURING_INSPECTION.with(|slot| slot.borrow_mut().take());
    if let Some(hook) = hook {
        hook();
    }
}

pub(super) fn at_content_seam(site: &'static str) {
    let hook = CONTENT_SEAM.with(|slot| {
        let mut slot = slot.borrow_mut();
        if slot.as_ref().is_some_and(|(expected, _)| *expected == site) {
            slot.take().map(|(_, hook)| hook)
        } else {
            None
        }
    });
    if let Some(hook) = hook {
        hook();
    }
}

struct ClearHook;
impl Drop for ClearHook {
    fn drop(&mut self) {
        AFTER_OBSERVATIONS.with(|slot| slot.borrow_mut().take());
        AT_REOPENED.with(|slot| slot.borrow_mut().take());
        DURING_INSPECTION.with(|slot| slot.borrow_mut().take());
        CONTENT_SEAM.with(|slot| slot.borrow_mut().take());
    }
}

fn checked<T>(result: NativeResult<T>) -> TestResult<T> {
    result.map_err(|_| "native-operation-failed")
}

fn proof(case: &'static str, name: &'static str, value: bool) -> TestResult<()> {
    println!("prefix-reopen-correction|{case}|{name}={value}");
    if value { Ok(()) } else { Err("proof-failed") }
}

// The exact protected ACL generated by the existing creation helper, not merely a
// protected-bit check. No SID/descriptor/ACL bytes are formatted, even on failure.
fn private_checks(security: &WindowsSecurityObservation) -> TestResult<[(&'static str, bool); 6]> {
    let descriptor = checked(private_security_descriptor(&security.current_user_sid))?;
    let mut present = 0;
    let mut defaulted = 0;
    let mut acl: *mut ACL = null_mut();
    // SAFETY: descriptor owns a valid self-relative security descriptor; outputs are writable.
    if unsafe { GetSecurityDescriptorDacl(descriptor.0, &mut present, &mut acl, &mut defaulted) }
        == 0
        || present == 0
        || acl.is_null()
    {
        return Err("private-descriptor-failed");
    }
    // Match inspect_security's representation exactly: allocated ACL capacity is not
    // security evidence. Preserve all in-use ACE bytes and canonicalize only AclSize.
    // SAFETY: ACL points within the still-live descriptor; validate before reading it.
    if unsafe { IsValidAcl(acl) } == 0 {
        return Err("private-descriptor-invalid-acl");
    }
    let mut size_info: ACL_SIZE_INFORMATION = unsafe { zeroed() };
    // SAFETY: ACL is valid; size_info is writable and has the requested structure/size.
    if unsafe {
        GetAclInformation(
            acl,
            (&mut size_info as *mut ACL_SIZE_INFORMATION).cast(),
            size_of::<ACL_SIZE_INFORMATION>() as u32,
            AclSizeInformation,
        )
    } == 0
    {
        return Err("private-descriptor-acl-size-failed");
    }
    // SAFETY: IsValidAcl succeeded, so the fixed header is readable.
    let declared_size = unsafe { (*acl).AclSize } as usize;
    let bytes_in_use = size_info.AclBytesInUse as usize;
    if declared_size < size_of::<ACL>()
        || bytes_in_use < size_of::<ACL>()
        || bytes_in_use > declared_size
    {
        return Err("private-descriptor-acl-size-invalid");
    }
    // SAFETY: bytes_in_use is validated within the live ACL's declared allocation.
    let mut expected =
        unsafe { std::slice::from_raw_parts(acl.cast::<u8>(), bytes_in_use) }.to_vec();
    expected[2..4].copy_from_slice(&(bytes_in_use as u16).to_le_bytes());
    Ok([
        (
            "owner-current-user",
            security.owner_sid == security.current_user_sid,
        ),
        ("dacl-protected", security.descriptor_control & 0x1000 != 0),
        ("dacl-present", security.dacl_present),
        ("dacl-not-null", !security.dacl_null),
        ("dacl-not-defaulted", !security.dacl_defaulted),
        (
            "expected-canonical-dacl-equal",
            security.dacl_bytes.as_ref() == expected.as_slice(),
        ),
    ])
}

fn private(security: &WindowsSecurityObservation) -> TestResult<bool> {
    Ok(private_checks(security)?.iter().all(|(_, passed)| *passed))
}

fn directory(parent: &str, component: &str) -> TestResult<String> {
    let receipt = checked(create_windows_private_directory(parent, component))?;
    if !private(&receipt.creation_security)? {
        return Err("fixture-not-private");
    }
    Ok(join_direct_child(parent, component))
}

const CONTENT: &[u8] = b"controlled immutable target bytes\n";

fn file(parent: &str, component: &str) -> TestResult<String> {
    let receipt = checked(create_windows_private_file(parent, component))?;
    if !private(&receipt.creation_security)? {
        return Err("fixture-not-private");
    }
    let path = join_direct_child(parent, component);
    let handle = checked(open_existing(&path, GENERIC_WRITE))?;
    let mut written = 0;
    // SAFETY: synchronous handle, live fixed input, writable byte count, no OVERLAPPED.
    let success = unsafe {
        WriteFile(
            handle.0,
            CONTENT.as_ptr(),
            CONTENT.len() as u32,
            &mut written,
            null_mut(),
        )
    };
    if success == 0 || written as usize != CONTENT.len() {
        return Err("fixture-write-failed");
    }
    Ok(path)
}

fn open_inspected(path: &str) -> TestResult<OpenedPath> {
    checked(open_admitted_path(
        path,
        FILE_READ_ATTRIBUTES | READ_CONTROL,
    ))
}

fn seed_timestamps(path: &str) -> TestResult<()> {
    let handle = checked(open_existing(path, FILE_WRITE_ATTRIBUTES))?;
    // Fixed historical values separate namespace mutation from creation without sleeps.
    // Zero preserves other fields. Actual observations, not these requested values,
    // determine whether the production predicate should refuse.
    let basic = FILE_BASIC_INFO {
        CreationTime: 0,
        LastAccessTime: 0,
        LastWriteTime: 125_911_584_000_000_000,
        ChangeTime: 125_911_584_000_000_000,
        FileAttributes: 0,
    };
    // SAFETY: live FILE_BASIC_INFO and correct size/class for a valid writable handle.
    if unsafe {
        SetFileInformationByHandle(
            handle.0,
            FileBasicInfo,
            (&basic as *const FILE_BASIC_INFO).cast(),
            size_of::<FILE_BASIC_INFO>() as u32,
        )
    } == 0
    {
        return Err("timestamp-seed-failed");
    }
    Ok(())
}

fn unchanged_target(a: &FixtureInspection, b: &FixtureInspection) -> bool {
    a.canonical_path == b.canonical_path
        && a.kind == b.kind
        && a.volume.identity == b.volume.identity
        && a.ancestry_reparse_free
        && b.ancestry_reparse_free
        && same_stable_observation(&a.object, &b.object)
}

// Includes access time for exact evidence binding, without changing the production
// predicate (which intentionally ignores access time). Nothing here is formatted.
fn exact_object(a: &WindowsObjectObservation, b: &WindowsObjectObservation) -> bool {
    same_stable_observation(a, b) && a.last_access_time == b.last_access_time
}

struct ReopenedObservation {
    index: usize,
    initial_canonical_path: String,
    initial_object: WindowsObjectObservation,
    reopened_canonical_path: String,
    reopened_object: WindowsObjectObservation,
}

struct Evidence {
    index: usize,
    initial_object: WindowsObjectObservation,
    before: FixtureInspection,
    after: FixtureInspection,
    initial_matched: bool,
    designated_non_root_ancestor: bool,
    mutation_completed: bool,
    fields: Vec<&'static str>,
}

fn at_seam(
    observations: &[AdmissionPrefixObservation],
    ancestor: &str,
    mutate: bool,
) -> TestResult<Evidence> {
    // Raw open + existing inspection avoids a second admission as the observation source.
    // Compare it to the REAL initial prefix observation before causing the mutation.
    let handle = checked(open_existing(ancestor, FILE_READ_ATTRIBUTES | READ_CONTROL))?;
    let opened = OpenedPath {
        canonical_path: checked(final_path(handle.0))?,
        handle,
        ancestry_reparse_free: true,
    };
    let before = checked(fixture_opened(&opened))?;
    let index = observations
        .iter()
        .position(|p| p.canonical_path == before.canonical_path)
        .ok_or("designated-prefix-missing")?;
    let initial = &observations[index];
    let designated_non_root_ancestor = prefix_role(index, observations.len() - 1) == "ancestor";
    let initial_matched = same_stable_observation(&initial.object, &before.object);
    if !designated_non_root_ancestor || !initial_matched {
        return Err("seam-precondition-failed");
    }
    if mutate {
        // This invokes the real protected creation helper with its normal parent/child
        // inspection. The one-shot hook is already consumed, including for nested opens.
        let receipt = checked(create_windows_private_file(ancestor, "unrelated-sibling"))?;
        if !private(&receipt.creation_security)?
            || receipt.created.kind != "regular-file"
            || receipt.created.object.size != "0000000000000000"
        {
            return Err("mutation-proof-failed");
        }
    }
    let after = checked(fixture_opened(&opened))?;
    let mut fields = stable_fields(&initial.object, &after.object);
    if initial.canonical_path != after.canonical_path {
        fields.push("canonicalPath");
    }
    Ok(Evidence {
        index,
        initial_object: initial.object.clone(),
        before,
        after,
        initial_matched,
        designated_non_root_ancestor,
        mutation_completed: mutate,
        fields,
    })
}

fn run_case(root: &str, case: &'static str, is_directory: bool, mutate: bool) -> TestResult<()> {
    proof(case, "case-started", true)?;
    let ancestor = directory(root, case)?;
    let branch = directory(&ancestor, "target-branch")?;
    let target = if is_directory {
        directory(&branch, "target")?
    } else {
        file(&branch, "target")?
    };
    let content_path = if is_directory {
        file(&target, "content")?
    } else {
        target.clone()
    };
    seed_timestamps(&ancestor)?;

    let target_before = checked(fixture_path(&target))?;
    let content_before = checked(fixture_path(&content_path))?;
    let bytes_before = checked(read_windows_file_stable(
        &content_path,
        CONTENT.len() as u32,
    ))?;
    // The bound is the exact fixture cardinality, not a retry or arbitrary workload cap.
    let entries_before = if is_directory {
        let opened = checked(open_admitted_path(
            &target,
            FILE_LIST_DIRECTORY | FILE_READ_ATTRIBUTES | READ_CONTROL,
        ))?;
        Some(checked(enumerate_directory_pass(opened.handle.0, 1))?)
    } else {
        None
    };
    proof(
        case,
        "fixture-private",
        private(&target_before.security)? && private(&content_before.security)?,
    )?;
    proof(
        case,
        "target-type",
        target_before.kind
            == if is_directory {
                "directory"
            } else {
                "regular-file"
            },
    )?;
    proof(case, "initial-bytes", bytes_before.bytes == CONTENT)?;

    let evidence = Rc::new(RefCell::new(None));
    let sink = Rc::clone(&evidence);
    let reopened_evidence = Rc::new(RefCell::new(None));
    let reopened_sink = Rc::clone(&reopened_evidence);
    let hook_ancestor = ancestor.clone();
    let occupied = AFTER_OBSERVATIONS.with(|slot| slot.borrow().is_some())
        || AT_REOPENED.with(|slot| slot.borrow().is_some());
    if occupied {
        return Err("hook-already-installed");
    }
    let guard = ClearHook;
    AFTER_OBSERVATIONS.with(|slot| {
        *slot.borrow_mut() = Some(Box::new(move |observations| {
            let measured = at_seam(observations, &hook_ancestor, mutate);
            if let Ok(evidence) = &measured {
                let designated_index = evidence.index;
                AT_REOPENED.with(|slot| {
                    *slot.borrow_mut() =
                        Some(Box::new(move |index, initial, canonical, object| {
                            if index == designated_index {
                                *reopened_sink.borrow_mut() = Some(ReopenedObservation {
                                    index,
                                    initial_canonical_path: initial.canonical_path.clone(),
                                    initial_object: initial.object.clone(),
                                    reopened_canonical_path: canonical.to_owned(),
                                    reopened_object: object.clone(),
                                });
                            }
                        }));
                });
            }
            *sink.borrow_mut() = Some(measured);
        }))
    });
    let admission = open_admitted_path_with_final_share(
        &target,
        FILE_READ_ATTRIBUTES | READ_CONTROL,
        FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,
    );
    drop(guard);
    let evidence = evidence.borrow_mut().take().ok_or("hook-not-reached")??;
    let observed = reopened_evidence
        .borrow_mut()
        .take()
        .ok_or("actual-reopen-not-observed")?;
    proof(case, "initial-prefix-matched", evidence.initial_matched)?;
    proof(
        case,
        "designated-non-root-ancestor",
        evidence.designated_non_root_ancestor,
    )?;
    println!(
        "prefix-reopen-correction|{case}|mutation-performed={}",
        evidence.mutation_completed
    );
    proof(
        case,
        "mutation-matches-case",
        evidence.mutation_completed == mutate,
    )?;
    proof(
        case,
        "ancestor-identity-unchanged",
        same_directory_identity(&evidence.before, &evidence.after),
    )?;
    proof(
        case,
        "ancestor-security-unchanged",
        same_security_observation(&evidence.before.security, &evidence.after.security),
    )?;
    proof(
        case,
        "ancestor-private",
        private(&evidence.before.security)? && private(&evidence.after.security)?,
    )?;
    let predicate = evidence.before.canonical_path == evidence.after.canonical_path
        && same_stable_observation(&evidence.before.object, &evidence.after.object);
    println!("prefix-reopen-correction|{case}|ancestor-stable-predicate={predicate}");
    println!(
        "prefix-reopen-correction|{case}|object.lastWriteTime={}",
        evidence.before.object.last_write_time != evidence.after.object.last_write_time
    );
    println!(
        "prefix-reopen-correction|{case}|object.changeTime={}",
        evidence.before.object.change_time != evidence.after.object.change_time
    );
    if !mutate {
        proof(case, "control-predicate-true", predicate)?;
    }
    proof(
        case,
        "diagnostic-predicate-parity",
        predicate == evidence.fields.is_empty(),
    )?;

    proof(case, "old-predicate-matches-case", predicate != mutate)?;
    proof(
        case,
        "timestamp-only-difference",
        if mutate {
            evidence.fields == ["object.lastWriteTime", "object.changeTime"]
        } else {
            evidence.fields.is_empty()
        },
    )?;
    proof(
        case,
        "actual-reopen-is-designated-ancestor",
        observed.index == evidence.index
            && observed.initial_canonical_path == evidence.before.canonical_path,
    )?;
    proof(
        case,
        "actual-initial-observation-matches-seam",
        exact_object(&observed.initial_object, &evidence.initial_object),
    )?;
    proof(
        case,
        "actual-reopened-observation-matches-seam",
        observed.reopened_canonical_path == evidence.after.canonical_path
            && exact_object(&observed.reopened_object, &evidence.after.object),
    )?;
    proof(
        case,
        "corrected-admission-predicate-true",
        same_admission_observation(&observed.initial_object, &observed.reopened_object)
            && admission_fields(&observed.initial_object, &observed.reopened_object).is_empty(),
    )?;
    proof(case, "admitted", admission.is_ok())?;
    let opened = checked(admission)?;
    proof(
        case,
        "admitted-target-unchanged",
        unchanged_target(&target_before, &checked(fixture_opened(&opened))?),
    )?;
    // Reopen by name after the admission attempt, so retained handles alone cannot hide
    // replacement. The whole target object predicate includes canonical identity/type.
    let target_after = checked(fixture_path(&target))?;
    let content_after = checked(fixture_path(&content_path))?;
    let bytes_after = checked(read_windows_file_stable(
        &content_path,
        CONTENT.len() as u32,
    ))?;
    proof(
        case,
        "target-canonical-identity-type-security-unchanged",
        unchanged_target(&target_before, &target_after),
    )?;
    proof(
        case,
        "content-file-identity-security-unchanged",
        unchanged_target(&content_before, &content_after),
    )?;
    proof(
        case,
        "file-bytes-unchanged",
        bytes_before.bytes == bytes_after.bytes && bytes_after.bytes == CONTENT,
    )?;
    if let Some(before) = entries_before {
        let opened = checked(open_admitted_path(
            &target,
            FILE_LIST_DIRECTORY | FILE_READ_ATTRIBUTES | READ_CONTROL,
        ))?;
        let after = checked(enumerate_directory_pass(opened.handle.0, 1))?;
        proof(
            case,
            "directory-target-contents-unchanged",
            before.len() == 1 && before == after,
        )?;
    }
    proof(case, "case-complete", true)
}

#[test]
#[ignore = "requires BAZFRAME_WIN32_PREFIX_REPRO_PARENT; retains new private fixtures"]
fn directory_admission_correction_regression() -> TestResult<()> {
    let run = || -> TestResult<()> {
        let parent = std::env::var("BAZFRAME_WIN32_PREFIX_REPRO_PARENT")
            .map_err(|_| "private-parent-env-required")?;
        let parent_opened = open_inspected(&parent)?;
        let parent_inspection = checked(fixture_opened(&parent_opened))?;
        let parent_is_directory = parent_inspection.kind == "directory";
        println!("prefix-reopen-correction|parent-admission|directory={parent_is_directory}");
        let checks = private_checks(&parent_inspection.security)?;
        // Emit every fixed prerequisite boolean before refusing, not just the first
        // failed check. No received error or security observation is ever formatted.
        for (name, passed) in &checks {
            println!("prefix-reopen-correction|parent-admission|{name}={passed}");
        }
        if !parent_is_directory || !checks.iter().all(|(_, passed)| *passed) {
            return Err("private-parent-required");
        }
        // Fixed no-replace namespace: never reuse any fixture from an earlier invocation.
        let root = directory(&parent, "prefix-reopen-correction")?;
        for (case, is_directory, mutate) in [
            ("file-control", false, false),
            ("directory-control", true, false),
            ("file-sibling-create", false, true),
            ("directory-sibling-create", true, true),
        ] {
            run_case(&root, case, is_directory, mutate)?;
        }
        run_admission_seams(&root)?;
        run_content_seams(&root)?;
        Ok(())
    };
    // Returning only a fixed literal also avoids a panic/backtrace on expected failures.
    // Never Debug/Display a native or OS error.
    run()
}

// Use the same setter/handle recipe during new-fixture construction and mutation.
// The redundant read ACE grants no principal any additional authority.
fn set_private_fixture_dacl(
    path: &str,
    user_sid: &str,
    redundant_read: bool,
) -> TestResult<OwnedHandle> {
    use windows_sys::Win32::Security::Authorization::SetSecurityInfo;
    use windows_sys::Win32::Storage::FileSystem::{FILE_GENERIC_READ, WRITE_DAC};
    let descriptor = if redundant_read {
        let sddl = wide(&format!(
            "O:{0}D:P(A;OICI;FA;;;{0})(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)(A;;FR;;;{0})",
            user_sid
        ));
        let mut descriptor = null_mut();
        // SAFETY: terminated SDDL, writable descriptor output, optional size omitted.
        if unsafe {
            ConvertStringSecurityDescriptorToSecurityDescriptorW(
                sddl.as_ptr(),
                SDDL_REVISION_1,
                &mut descriptor,
                null_mut(),
            )
        } == 0
        {
            return Err("security-fixture-descriptor-failed");
        }
        OwnedLocal(descriptor)
    } else {
        checked(private_security_descriptor(user_sid))?
    };
    let mut acl = null_mut();
    let mut present = 0;
    let mut defaulted = 0;
    // SAFETY: descriptor is live and valid; outputs are writable.
    if unsafe { GetSecurityDescriptorDacl(descriptor.0, &mut present, &mut acl, &mut defaulted) }
        == 0
        || present == 0
        || acl.is_null()
    {
        return Err("security-fixture-dacl-failed");
    }
    // Explicit standard read rights preserve open_existing's flags: GENERIC_READ
    // would also select its conditional FILE_FLAG_SEQUENTIAL_SCAN branch.
    let handle = checked(open_existing(
        path,
        FILE_GENERIC_READ | WRITE_DAC | FILE_WRITE_ATTRIBUTES,
    ))?;
    // SAFETY: valid handle and DACL; only DACL is selected, other pointers are unused.
    if unsafe {
        SetSecurityInfo(
            handle.0,
            SE_FILE_OBJECT,
            DACL_SECURITY_INFORMATION,
            null_mut(),
            null_mut(),
            acl,
            null_mut(),
        )
    } != ERROR_SUCCESS
    {
        return Err("security-fixture-write-failed");
    }
    Ok(handle)
}

// One construction-time application of the exact original DACL initializes the
// documented inheritance model, before any target baseline or mutation hook.
// Never called on retained fixtures; there is no retry, repair or normalization loop.
fn prepare_private_security(path: &str) -> TestResult<()> {
    use windows_sys::Win32::Security::SE_DACL_AUTO_INHERITED;
    let opened = open_inspected(path)?;
    let before = checked(fixture_opened(&opened))?;
    if !private(&before.security)? {
        return Err("security-preparation-private-failed");
    }
    drop(set_private_fixture_dacl(
        path,
        &before.security.current_user_sid,
        false,
    )?);
    let after = checked(fixture_path(path))?;
    if !same_directory_identity(&before, &after)
        || !before.ancestry_reparse_free
        || !after.ancestry_reparse_free
    {
        return Err("security-preparation-identity-failed");
    }
    if !private(&after.security)? {
        return Err("security-preparation-private-failed");
    }
    // No security field may differ except this documented bit becoming set.
    // If it was already set, the complete descriptor must remain equal.
    if after.security.descriptor_control
        != before.security.descriptor_control | u32::from(SE_DACL_AUTO_INHERITED)
        || security_fields(&before.security, &after.security)
            .iter()
            .any(|field| *field != "security.descriptorControl")
    {
        return Err("security-preparation-security-failed");
    }
    Ok(())
}

// Restore both content timestamps so the mutation refusal cannot rely on changeTime.
fn change_private_security(
    path: &str,
    before: &WindowsObjectObservation,
    user_sid: &str,
) -> TestResult<()> {
    let handle = set_private_fixture_dacl(path, user_sid, true)?;
    let basic = FILE_BASIC_INFO {
        CreationTime: 0,
        LastAccessTime: 0,
        LastWriteTime: u64::from_str_radix(&before.last_write_time, 16)
            .map_err(|_| "timestamp-parse-failed")? as i64,
        ChangeTime: u64::from_str_radix(&before.change_time, 16)
            .map_err(|_| "timestamp-parse-failed")? as i64,
        FileAttributes: 0,
    };
    // SAFETY: live writable handle, valid fixed input and size/class.
    if unsafe {
        SetFileInformationByHandle(
            handle.0,
            FileBasicInfo,
            (&basic as *const FILE_BASIC_INFO).cast(),
            size_of::<FILE_BASIC_INFO>() as u32,
        )
    } == 0
    {
        return Err("security-timestamp-restore-failed");
    }
    Ok(())
}

fn run_admission_seams(root: &str) -> TestResult<()> {
    for (case, prefix, is_directory, security_change) in [
        ("final-directory-timestamps", true, true, false),
        ("inspect-directory-timestamps", false, true, false),
        ("final-directory-security", true, true, true),
        ("ancestor-directory-security", true, true, true),
        ("inspect-directory-security", false, true, true),
        ("final-file-timestamps", true, false, false),
        ("inspect-file-timestamps", false, false, false),
    ] {
        proof(case, "case-started", true)?;
        let ancestor = case == "ancestor-directory-security";
        let parent = directory(root, case)?;
        if security_change && ancestor {
            prepare_private_security(&parent)?;
        }
        let target = if is_directory {
            directory(&parent, "target")?
        } else {
            file(&parent, "target")?
        };
        if security_change && !ancestor {
            prepare_private_security(&target)?;
        }
        if is_directory {
            seed_timestamps(&target)?;
        }
        let inspected_path = if ancestor { &parent } else { &target };
        let target_before = checked(fixture_path(&target))?;
        let opened = open_inspected(inspected_path)?;
        let before = checked(fixture_opened(&opened))?;
        let result = Rc::new(RefCell::new(None));
        let sink = Rc::clone(&result);
        let mutation_path = inspected_path.clone();
        let mutation_before = before.object.clone();
        let user_sid = before.security.current_user_sid.clone();
        let mutation = move || {
            *sink.borrow_mut() = Some(if security_change {
                change_private_security(&mutation_path, &mutation_before, &user_sid)
            } else if is_directory {
                directory(&mutation_path, "new-child").map(|_| ())
            } else {
                seed_timestamps(&mutation_path)
            });
        };
        let guard = ClearHook;
        if prefix {
            AFTER_OBSERVATIONS
                .with(|slot| *slot.borrow_mut() = Some(Box::new(move |_| mutation())));
        } else {
            DURING_INSPECTION.with(|slot| *slot.borrow_mut() = Some(Box::new(mutation)));
        }
        let admission = if prefix {
            open_inspected_native(&target).map(|_| ())
        } else {
            inspect_opened_path(&opened).map(|_| ())
        };
        drop(guard);
        result
            .borrow_mut()
            .take()
            .ok_or("mutation-hook-not-reached")??;
        let after = checked(fixture_path(inspected_path))?;
        if ancestor {
            proof(
                case,
                "target-unchanged",
                unchanged_target(&target_before, &checked(fixture_path(&target))?),
            )?;
        }
        proof(
            case,
            "physical-identity-preserved",
            before.canonical_path == after.canonical_path
                && before.object.file_id == after.object.file_id
                && before.object.volume_identity == after.object.volume_identity
                && before.kind == after.kind
                && after.ancestry_reparse_free,
        )?;
        if security_change {
            proof(
                case,
                "object-fully-stable",
                same_stable_observation(&before.object, &after.object),
            )?;
            proof(
                case,
                "security-bytes-changed-only",
                security_fields(&before.security, &after.security) == ["security.daclBytes"],
            )?;
        } else {
            proof(
                case,
                "exact-security-preserved",
                same_security_observation(&before.security, &after.security),
            )?;
            proof(
                case,
                "old-full-predicate-false",
                !same_stable_observation(&before.object, &after.object),
            )?;
        }
        if security_change {
            proof(case, "security-only-change-admitted", admission.is_ok())?;
        } else if is_directory {
            proof(
                case,
                "corrected-admission-predicate-true",
                same_admission_observation(&before.object, &after.object),
            )?;
            proof(case, "admitted", admission.is_ok())?;
            proof(
                case,
                "content-comparison-still-refuses",
                !same_path_inspection(&before, &after),
            )?;
        } else {
            let error = admission.err().ok_or("expected-refusal-missing")?;
            let fields = stable_fields(&before.object, &after.object);
            let expected = read_changed::<()>(
                if prefix {
                    "reopened-prefix"
                } else {
                    "inspect-opened-path"
                },
                is_directory,
                if ancestor {
                    "ancestor"
                } else if prefix {
                    "final"
                } else {
                    "none"
                },
                fields,
            )
            .err()
            .ok_or("diagnostic-construction-failed")?;
            proof(
                case,
                "exact-native-refusal",
                error.status == expected.status && error.reason == expected.reason,
            )?;
        }
        proof(case, "case-complete", true)?;
    }
    let path = directory(root, "missing-read-control")?;
    let handle = checked(open_existing(&path, FILE_READ_ATTRIBUTES))?;
    let opened = OpenedPath {
        canonical_path: checked(final_path(handle.0))?,
        handle,
        ancestry_reparse_free: true,
    };
    let admitted = inspect_opened_path(&opened);
    proof(
        "missing-read-control",
        "physical-inspection-without-read-control",
        admitted.is_ok(),
    )
}

fn open_inspected_native(path: &str) -> NativeResult<OpenedPath> {
    open_admitted_path(path, FILE_READ_ATTRIBUTES)
}

fn run_content_seams(root: &str) -> TestResult<()> {
    for case in [
        "enumeration-between-passes",
        "enumeration-after-passes",
        "stable-read-final",
    ] {
        let parent = directory(root, case)?;
        let target = if case == "stable-read-final" {
            file(&parent, "target")?
        } else {
            directory(&parent, "target")?
        };
        if case != "stable-read-final" {
            seed_timestamps(&target)?;
        }
        let sink = Rc::new(RefCell::new(None));
        let result = Rc::clone(&sink);
        let mutation_path = target.clone();
        let guard = ClearHook;
        CONTENT_SEAM.with(|slot| {
            *slot.borrow_mut() = Some((
                case,
                Box::new(move || {
                    *result.borrow_mut() = Some(if case == "enumeration-between-passes" {
                        directory(&mutation_path, "new-child").map(|_| ())
                    } else {
                        seed_timestamps_different(&mutation_path)
                    });
                }),
            ))
        });
        let operation = if case == "stable-read-final" {
            read_windows_file_stable(&target, CONTENT.len() as u32).map(|_| ())
        } else {
            enumerate_windows_directory_stable(&target, 1).map(|_| ())
        };
        drop(guard);
        sink.borrow_mut()
            .take()
            .ok_or("content-hook-not-reached")??;
        let error = operation.err().ok_or("content-refusal-missing")?;
        proof(
            case,
            "content-change-refused",
            if case == "stable-read-final" {
                error.status == "ERR_WIN32_READ_CHANGED"
                    && error
                        .reason
                        .starts_with("read-change|stable-read-final|regular-file|none|")
            } else {
                error.status == "ERR_WIN32_ENUMERATION_CHANGED"
            },
        )?;
    }
    Ok(())
}

fn seed_timestamps_different(path: &str) -> TestResult<()> {
    // A second fixed historical value guarantees metadata-only drift in enumeration;
    // unlike sibling creation this leaves both already-consumed entry passes equal.
    let handle = checked(open_existing(path, FILE_WRITE_ATTRIBUTES))?;
    let basic = FILE_BASIC_INFO {
        CreationTime: 0,
        LastAccessTime: 0,
        LastWriteTime: 125_911_585_000_000_000,
        ChangeTime: 125_911_585_000_000_000,
        FileAttributes: 0,
    };
    // SAFETY: correct fixed input/class/size and valid writable handle.
    if unsafe {
        SetFileInformationByHandle(
            handle.0,
            FileBasicInfo,
            (&basic as *const FILE_BASIC_INFO).cast(),
            size_of::<FILE_BASIC_INFO>() as u32,
        )
    } == 0
    {
        return Err("timestamp-seed-failed");
    }
    Ok(())
}
