import { createHash } from 'node:crypto';
import { afterEach,describe,expect,it } from 'vitest';
import { mkdir,writeFile } from 'node:fs/promises';
import { createTempDirectory,type TempDirectory } from '../../helpers/temp-directory.js';
import { publishStoredBlob } from '../../../src/profile-publishing/blob-store.js';
import { artifactTreeId,publishArtifactTree,readArtifactTree,type ArtifactTreeManifestV1 } from '../../../src/profile-publishing/artifact-tree.js';
import { withProfileOperationLocks,type OperationMutationAuthority } from '../../../src/profile-publishing/profile-operation-lock.js';
import { profilePublishingTreeRoot } from '../../../src/state/paths.js';
let temporary:TempDirectory|undefined;afterEach(async()=>{await temporary?.cleanup();temporary=undefined;});
const bytes=Buffer.from('skill\n'),sha=createHash('sha256').update(bytes).digest('hex');const manifest:ArtifactTreeManifestV1={schemaVersion:1,kind:'bazframe-artifact-tree',role:'skill',files:[{path:'SKILL.md',sha256:sha,bytes:bytes.length,executable:false}]};
describe('authorized artifact mutation',()=>{
 it('publishes exact blobs and committed trees, then converges through reuse',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');await withProfileOperationLocks(temporary.root,['@store'],async(authority)=>{expect((await publishStoredBlob(temporary!.root,authority,bytes,sha)).reused).toBe(false);expect((await publishStoredBlob(temporary!.root,authority,bytes,sha)).reused).toBe(true);const first=await publishArtifactTree(temporary!.root,authority,manifest);expect(first).toMatchObject({treeId:artifactTreeId(manifest),reused:false});expect(await publishArtifactTree(temporary!.root,authority,manifest)).toMatchObject({treeId:first.treeId,reused:true});expect((await readArtifactTree(temporary!.root,first.treeId)).manifest).toEqual(manifest);});});
 it('rejects forged or expired authority and digest mismatch',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');await expect(publishStoredBlob(temporary.root,{} as OperationMutationAuthority,bytes,sha)).rejects.toMatchObject({code:'PROFILE_OPERATION_AUTHORITY_INVALID'});let expired!:OperationMutationAuthority;await withProfileOperationLocks(temporary.root,['@store'],async(authority)=>{expired=authority;await expect(publishStoredBlob(temporary!.root,authority,bytes,'0'.repeat(64))).rejects.toMatchObject({code:'PROFILE_BLOB_INVALID'});});await expect(publishStoredBlob(temporary.root,expired,bytes,sha)).rejects.toMatchObject({code:'PROFILE_OPERATION_AUTHORITY_INVALID'});});
 it('retains and refuses an occupied uncommitted tree',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');await withProfileOperationLocks(temporary.root,['@store'],async(authority)=>{await publishStoredBlob(temporary!.root,authority,bytes,sha);const path=`${profilePublishingTreeRoot(temporary!.root)}/${artifactTreeId(manifest)}`;await mkdir(path,{recursive:true});await writeFile(`${path}/foreign`,'x');await expect(publishArtifactTree(temporary!.root,authority,manifest)).rejects.toMatchObject({code:'PROFILE_ARTIFACT_TREE_OCCUPIED'});await expect(readArtifactTree(temporary!.root,artifactTreeId(manifest))).rejects.toBeDefined();});});
});
