import { afterEach, describe, expect, it } from 'vitest';
import { fork, type ChildProcess } from 'node:child_process';
import { mkdir, readdir } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { createTempDirectory, type TempDirectory } from '../../helpers/temp-directory.js';
import { assertOperationMutationAuthority, profileOperationSocketPath, withProfileOperationLocks, type OperationMutationAuthority } from '../../../src/profile-publishing/profile-operation-lock.js';
import { profilePublishingOperationLockRoot } from '../../../src/state/paths.js';
let temporary:TempDirectory|undefined;let child:ChildProcess|undefined;
afterEach(async()=>{child?.kill('SIGKILL');child=undefined;await temporary?.cleanup();temporary=undefined;});
async function holder(path:string):Promise<ChildProcess>{await mkdir(profilePublishingOperationLockRoot(temporary!.root),{recursive:true});const process=fork(new URL('../../fixtures/profile-operation-lock-holder.mjs',import.meta.url),[],{env:{...globalThis.process.env,LOCK_PATH:path},stdio:['ignore','ignore','ignore','ipc']});await new Promise<void>((resolve,reject)=>{process.once('message',()=>resolve());process.once('error',reject);});return process;}
describe('profile operation lock',()=>{
 it('rejects forged, wrong-key, wrong-home, and expired authority',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');const home=temporary.root;let expired:OperationMutationAuthority|undefined;await withProfileOperationLocks(home,['work','@store'],async(authority)=>{expired=authority;expect(()=>assertOperationMutationAuthority(authority,home,['work','@store'])).not.toThrow();expect(()=>assertOperationMutationAuthority(authority,home,['other'])).toThrow();expect(()=>assertOperationMutationAuthority(authority,`${home}-other`,['work'])).toThrow();});expect(()=>assertOperationMutationAuthority(expired!,home,['work'])).toThrow();expect(()=>assertOperationMutationAuthority({} as OperationMutationAuthority,home,['work'])).toThrow();});
 it('detects a live socket and recovers a refused stale socket after process death',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');const path=profileOperationSocketPath(temporary.root,'work');child=await holder(path);await expect(withProfileOperationLocks(temporary.root,['work'],async()=>undefined)).rejects.toMatchObject({code:'PROFILE_OPERATION_LOCK_BUSY'});child.kill('SIGKILL');await new Promise<void>((resolve)=>child!.once('exit',()=>resolve()));child=undefined;await expect(withProfileOperationLocks(temporary.root,['work'],async()=> 'ok')).resolves.toBe('ok');});
 it('uses live takeover claims to prevent acquisition through a stale-replacement gap',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');const path=profileOperationSocketPath(temporary.root,'work');const claim=join(profilePublishingOperationLockRoot(temporary.root),`.c${basename(path).slice(0,9)}.${'a'.repeat(10)}`);child=await holder(claim);await expect(withProfileOperationLocks(temporary.root,['work'],async()=>undefined)).rejects.toMatchObject({code:'PROFILE_OPERATION_LOCK_BUSY'});child.kill('SIGKILL');await new Promise<void>((resolve)=>child!.once('exit',()=>resolve()));child=undefined;await expect(withProfileOperationLocks(temporary.root,['work'],async()=> 'ok')).resolves.toBe('ok');});
 it('reclaims an orphan private owner socket left before canonical linking',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');const root=profilePublishingOperationLockRoot(temporary.root);const orphan=join(root,`.o-${'a'.repeat(19)}`);child=await holder(orphan);child.kill('SIGKILL');await new Promise<void>((resolve)=>child!.once('exit',()=>resolve()));child=undefined;await expect(withProfileOperationLocks(temporary.root,['work'],async()=>undefined)).resolves.toBeUndefined();expect(await readdir(root)).toEqual([]);});
 it('acquires multiple keys in canonical order and rejects empty or duplicate sets',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');await expect(withProfileOperationLocks(temporary.root,['z','a','@store'],async(authority)=>{assertOperationMutationAuthority(authority,temporary!.root,['a','z','@store']);})).resolves.toBeUndefined();await expect(withProfileOperationLocks(temporary.root,[],async()=>undefined)).rejects.toMatchObject({code:'PROFILE_OPERATION_LOCK_INVALID'});await expect(withProfileOperationLocks(temporary.root,['a','a'],async()=>undefined)).rejects.toMatchObject({code:'PROFILE_OPERATION_LOCK_INVALID'});});
 it('fails closed with the specific diagnostic when the Unix socket path is unsupported',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');const home=join(temporary.root,'x'.repeat(110));await expect(withProfileOperationLocks(home,['work'],async()=>undefined)).rejects.toMatchObject({code:'PROFILE_OPERATION_LOCK_PATH_UNSUPPORTED'});});
});
