import { afterEach, describe, expect, it } from 'vitest';
import { createTempDirectory,type TempDirectory } from '../../helpers/temp-directory.js';
import { mkdir, readdir, symlink } from 'node:fs/promises';
import { join } from 'node:path';
import { decodeTransactionJournalBytes,encodeTransactionJournal,isTransactionJournalName,readTransactionJournal,transitionTransactionJournal,writeTransactionJournal,type CandidateSwapJournalV1,type PublicationJournalV1,type RemoveProfileJournalV1,type RenameProfileJournalV1 } from '../../../src/profile-publishing/transaction-journal.js';
import { withProfileOperationLocks } from '../../../src/profile-publishing/profile-operation-lock.js';
const tx='0123456789abcdef0123456789abcdef',sha='a'.repeat(64),sha2='b'.repeat(64);let temporary:TempDirectory|undefined;afterEach(async()=>{await temporary?.cleanup();temporary=undefined;});
const candidate:CandidateSwapJournalV1={schemaVersion:1,kind:'candidate-swap',transactionId:tx,operation:'fresh-import',profileName:'work',expectedOld:{kind:'absent'},candidate:{token:`candidate:${tx}`,identity:null,sidecarSha256:null,profileClosureSha256:null},backup:null,activeProfileBefore:null,phase:'PLANNED',possiblePackageEffects:[]};
const rename:RenameProfileJournalV1={schemaVersion:1,kind:'rename-profile',transactionId:tx,oldName:'work',newName:'work-new',expectedOld:{identity:'1:2',sidecarSha256:null,profileClosureSha256:sha},expectedNew:{kind:'absent'},activeBefore:'work',activeAfter:'work-new',favoritesBeforeSha256:null,favoritesAfterCanonicalBytesSha256:sha2,phase:'INTENT'};
const remove:RemoveProfileJournalV1={schemaVersion:1,kind:'remove-profile',transactionId:tx,profileName:'work',expectedProfile:{identity:'1:2',sidecarSha256:null,profileClosureSha256:sha},quarantine:{token:`backup:${tx}`},activeBefore:'other',activeBeforeSha256:sha2,favoritesBeforeSha256:sha,favoritesAfterCanonicalBytesSha256:sha2,phase:'INTENT'};
const publication:PublicationJournalV1={schemaVersion:1,kind:'publication',transactionId:tx,profileName:'work',expectedProfile:{identity:'1:2',sidecarSha256:null,profileClosureSha256:sha},origin:'github.com/user-name/work',expectedBaseCommit:null,capturedManifestSha256:sha2,originalVisibility:'absent',desiredVisibility:'private',repositoryCreated:false,repositoryId:null,observedCommit:null,phase:'INTENT'};
describe('transaction journal',()=>{
 it.each([candidate,rename,remove,publication])('round trips canonical $kind bytes',(journal)=>{const bytes=Buffer.from(encodeTransactionJournal(journal));expect(decodeTransactionJournalBytes(bytes)).toEqual(journal);expect(()=>decodeTransactionJournalBytes(Buffer.from(bytes.toString().replace('  "kind"',' "kind"')))).toThrow();});
 it('enforces directed monotonic transitions',()=>{const materializing=transitionTransactionJournal(candidate,'MATERIALIZING');expect(materializing.phase).toBe('MATERIALIZING');expect(()=>transitionTransactionJournal(candidate,'CANDIDATE_READY')).toThrow();expect(()=>transitionTransactionJournal({...candidate,phase:'COMMITTED'},'AMBIGUOUS')).toThrow();expect(transitionTransactionJournal(candidate,'ABORTED').phase).toBe('ABORTED');expect(transitionTransactionJournal(publication,'AMBIGUOUS').phase).toBe('AMBIGUOUS');expect(transitionTransactionJournal(remove,'FAVORITES_MUTATION_INTENT').phase).toBe('FAVORITES_MUTATION_INTENT');expect(()=>transitionTransactionJournal(remove,'DIRECTORY_QUARANTINE_INTENT')).toThrow();});
 it('persists only initial creation and exact monotonic updates with live authority',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');await withProfileOperationLocks(temporary.root,['work','@store'],async(authority)=>{await expect(writeTransactionJournal(temporary!.root,authority,candidate)).resolves.toEqual(candidate);expect(await readTransactionJournal(temporary!.root,tx)).toEqual(candidate);await expect(writeTransactionJournal(temporary!.root,authority,{...candidate,phase:'CANDIDATE_READY'})).rejects.toBeDefined();const materializing={...candidate,phase:'MATERIALIZING' as const};await expect(writeTransactionJournal(temporary!.root,authority,materializing)).resolves.toEqual(materializing);await expect(writeTransactionJournal(temporary!.root,authority,{...materializing,profileName:'other',phase:'PACKAGES_LAST'})).rejects.toBeDefined();},tx);expect(isTransactionJournalName(`${tx}.json`)).toBe(true);expect(isTransactionJournalName(`x${tx}.json`)).toBe(false);});
 it('rejects wrong authority, cross-transaction tokens, and malformed values',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');await withProfileOperationLocks(temporary.root,['other','@store'],async(authority)=>{await expect(writeTransactionJournal(temporary!.root,authority,candidate)).rejects.toMatchObject({code:'PROFILE_OPERATION_AUTHORITY_INVALID'});},tx);expect(()=>encodeTransactionJournal({...candidate,transactionId:'bad'})).toThrow();expect(()=>encodeTransactionJournal({...candidate,candidate:{...candidate.candidate,token:`candidate:${'f'.repeat(32)}`}})).toThrow();expect(()=>encodeTransactionJournal({...candidate,expectedOld:{kind:'physical-directory',identity:'1:2',sidecarSha256:null,profileClosureSha256:sha},operation:'update',backup:{token:`backup:${'f'.repeat(32)}`,identity:'1:2',profileClosureSha256:sha}})).toThrow();expect(()=>encodeTransactionJournal({...publication,expectedBaseCommit:'bad'})).toThrow();expect(()=>encodeTransactionJournal({...remove,activeBefore:'work'})).toThrow();expect(()=>encodeTransactionJournal({...remove,quarantine:{token:'backup:bad'}})).toThrow();expect(()=>encodeTransactionJournal({...remove,favoritesBeforeSha256:null})).toThrow();});
 it('rejects a linked transaction namespace without writing through it',async()=>{temporary=await createTempDirectory('/tmp/bzf-op-');const outside=join(temporary.root,'outside');await mkdir(outside);await mkdir(join(temporary.root,'profile-publishing'));await symlink(outside,join(temporary.root,'profile-publishing','transactions'));await withProfileOperationLocks(temporary.root,['work','@store'],async(authority)=>{await expect(writeTransactionJournal(temporary!.root,authority,candidate)).rejects.toBeDefined();},tx);expect(await readdir(outside)).toEqual([]);});
 it('persists canonical generic GitHub profile repository names',()=>{const generic={...publication,origin:`github.com/user-name/profile_name-${'a'.repeat(70)}`};expect(decodeTransactionJournalBytes(Buffer.from(encodeTransactionJournal(generic)))).toEqual(generic);});
});
