import { spawn } from 'node:child_process';
import { readFile, stat, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { createTempDirectory, type TempDirectory } from '../helpers/temp-directory.js';

const cliPath=fileURLToPath(new URL('../../dist/cli.js',import.meta.url));
const directories:TempDirectory[]=[];
function runBuiltCli(path:string,args:readonly string[],cwd:string,environment:NodeJS.ProcessEnv):Promise<{status:number|null;stdout:string;stderr:string}>{return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path,...args],{cwd,env:environment,stdio:['ignore','pipe','pipe'],shell:false});let stdout='',stderr='';child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stdout.on('data',(value:string)=>stdout+=value);child.stderr.on('data',(value:string)=>stderr+=value);child.once('error',reject);child.once('close',status=>resolve({status,stdout,stderr}));});}
afterEach(async()=>Promise.all(directories.splice(0).map(item=>item.cleanup())));
async function archiveFixture(){const directory=await createTempDirectory('/tmp/bzf-import-');directories.push(directory);const cwd=await directory.mkdir('cwd');const sourceHome=directory.path('source');const environment={...process.env,BAZFRAME_HOME:sourceHome,NO_COLOR:'1'};await runBuiltCli(cliPath,['profile','add','portable'],cwd,environment);await directory.write('source/profiles/portable/AGENTS.md','portable instructions\n');const archive=directory.path('portable.zip');const exported=await runBuiltCli(cliPath,['profile','export','--profile','portable','--output',archive],cwd,environment);expect(exported.status).toBe(0);return{directory,cwd,archive,environment};}

describe('replacement profile import CLI',()=>{
 it('dry-runs a ZIP without creating BAZFRAME_HOME or changing the archive',async()=>{const f=await archiveFixture();const before=await readFile(f.archive);const home=f.directory.path('dry-home');const result=await runBuiltCli(cliPath,['profile','import','--dry-run',f.archive,'--json'],f.cwd,{...f.environment,BAZFRAME_HOME:home});expect(result).toMatchObject({status:0,stderr:''});expect(JSON.parse(result.stdout)).toMatchObject({schemaVersion:2,command:'profile.import',outcome:'success',result:{mode:'dry-run',profile:null,effects:{localStateWritten:false,profilePublished:false,cacheWritten:false,lockAcquired:false,buildExecuted:false,loginStarted:false}}});await expect(stat(home)).rejects.toMatchObject({code:'ENOENT'});expect(await readFile(f.archive)).toEqual(before);});
 it('imports an independent inactive ZIP with schema-v2 effects',async()=>{const f=await archiveFixture();const home=f.directory.path('target');const result=await runBuiltCli(cliPath,['profile','import',f.archive,'--json'],f.cwd,{...f.environment,BAZFRAME_HOME:home});expect(result.status).toBe(0);expect(JSON.parse(result.stdout)).toMatchObject({schemaVersion:2,outcome:'success',result:{source:{kind:'zip'},resolvedName:'portable',profile:{name:'portable',active:false,completeness:'complete',publication:null},effects:{localStateWritten:true,profilePublished:true,lockAcquired:true}}});expect(await readFile(`${home}/profiles/portable/AGENTS.md`,'utf8')).toBe('portable instructions\n');await expect(stat(`${home}/active-profile`)).rejects.toMatchObject({code:'ENOENT'});});
 it('returns a noninteractive collision refusal and lets --yes choose the safe suffix',async()=>{const f=await archiveFixture();const home=f.directory.path('target');const env={...f.environment,BAZFRAME_HOME:home};expect((await runBuiltCli(cliPath,['profile','import',f.archive],f.cwd,env)).status).toBe(0);const refused=await runBuiltCli(cliPath,['profile','import',f.archive,'--json'],f.cwd,env);expect(refused.status).toBe(2);expect(JSON.parse(refused.stdout)).toMatchObject({outcome:'refusal',refusal:{code:'PROFILE_IMPORT_COLLISION_DECISION_REQUIRED',interaction:{suggestedName:'portable-1'}}});const suffixed=await runBuiltCli(cliPath,['profile','import',f.archive,'--yes','--json'],f.cwd,env);expect(suffixed.status).toBe(0);expect(JSON.parse(suffixed.stdout)).toMatchObject({result:{resolvedName:'portable-1',collisionResolution:'safe-suffix'}});expect((await stat(`${home}/profiles/portable-1`)).isDirectory()).toBe(true);});
 it('keeps --yes distinct from destructive overwrite and preserves active selection during explicit overwrite',async()=>{const f=await archiveFixture();const home=f.directory.path('target');const env={...f.environment,BAZFRAME_HOME:home};expect((await runBuiltCli(cliPath,['profile','import',f.archive],f.cwd,env)).status).toBe(0);expect((await runBuiltCli(cliPath,['profile','use','portable'],f.cwd,env)).status).toBe(0);await writeFile(`${home}/profiles/portable/AGENTS.md`,'locally changed\n');const overwritten=await runBuiltCli(cliPath,['profile','import',f.archive,'--overwrite','--json'],f.cwd,env);expect(overwritten.status).toBe(0);expect(JSON.parse(overwritten.stdout)).toMatchObject({result:{resolvedName:'portable',collisionResolution:'overwrite',profile:{active:true}}});expect(await readFile(`${home}/active-profile`,'utf8')).toBe('portable\n');expect(await readFile(`${home}/profiles/portable/AGENTS.md`,'utf8')).toBe('portable instructions\n');});
});
